### ISSUE TITLE
[question] Multiple FASTQs per sample

### ISSUE THREAD

**Issue by embatty** [bactopia/bactopia#121]
I have some samples which have multiple sets of paired FASTQ files from different sequencing runs. Is it possible to set up an input FOFN so they can be automatically combined by Bactopia?

**Comment by rpetit3** [comment]
Hi @embatty!

I don't see this being too much of a problem. 

Do you think the merger should happen at the FOFN creation step or the Bactopia analysis pipeline step? I'm personally leaning towards the FOFN step because I'm already checking for duplicate samples and wouldn't have to change the bactopia analysis pipeline.

Only issue I see is the data being duplicated my cause storage problems and maybe some confusion on what's merged and what's not 6 months later. It would probably be best to create a folder to put the merged fastqs in. This way the original data is untouched and you can just delete the folder if you want.

What are your thoughts?

**Comment by embatty** [comment]
Hi @rpetit3, 

When you say 'the FOFN creation step', do you mean while running `bactopia prepare`? Personally I think I would lean towards having it in the actual pipeline, then my FOFN would point directly to the raw data I used rather than the merged files. I will definitely delete the merged files and keep only the original data, so having them in a different directory would be ideal. But if it's much easier to put it outside the pipeline, then that would work fine as well.

**Comment by rpetit3** [comment]
You are correct! I was referring to the `bactopia prepare` step. This way the FOFN would maintain 1 sample per line and require no changes on the Bactopia analysis pipeline side

**Comment by uloeber** [comment]
Hi both,
if this refers to the "Multiple Samples" description, would I create a text file like:
sample_1 rep1_R1.fq rep1_R2.fq rep2_R1 rep2_R2.fq
sample_2 x_r1.fq x_r2.fq...
?
This is very interesting to me as well. @rpetit3 , can I even give the assigned species alongside or is the sample list used for one isolate at a time for example? Not sure whether this makes sense to you, I'll try to describe the problem. We have isolated genomes and sequenced them and obviously replicates from the same strands have been sequenced. I would like to pool them for reassembly, while the taxonomic classification has been performed already (handling all samples separately) and like to include this as input for prokka as well.

**Comment by rpetit3** [comment]
I'm putting this info here, for reference so we don't have to go back to docs to find it. The FOFN is tab-delimited and has the following collums (See. https://bactopia.github.io/usage-basic/#the-fofn-format):

1. `sample`: A unique prefix, or unique name, to be used for naming output files
2. `runtype`: Informs Bactopia what type of input the sample is
3. `r1`: If paired-end, the first pair of reads, else the single-end reads
4. `r2`: If paired-end, the second pair of reads
5. `extra`: Either the assembly or long reads associated with a sample.

So what @embatty  is suggesting is `r1` and `r2` columns could have multiple FASTQs for a sample. (correct me if I'm wrong @embatty!)

```
my_sample    paired-end    my_sample-s1_R1.fastq.gz,my_sample-s2_R1.fastq.gz    my_sample-s1_R2.fastq.gz,my_sample-s2_R2.fastq.gz 
```

Bactopia would recognize that and merge them in the `bactopia` pipeline. Honestly, that is starting to look as the better option (tyvm @embatty). The FASTQs would be merged in the `gather_fastqs` step and everything goes forward (yay!).

Haha, we have three people that need this (myself included) feature, so, yeah let's do it!

Now @uloeber, you want to be able to also specify the species for datasets as well. I think for a single species, no problem! By that I mean, I add a `species` column to the FOFN and all the samples are the same species. 

I think it becomes more difficult if the directory contains FASTQs for multiple species. At that point, unless there's a pattern that matches the species (e.g. SA -> S. aureus, BA -> B. anthracis, EC -> E. coli etc...), I don't think I want to support creating a FOFN for multiple species. Another option would be the user gives a file containing the sample and and species (which what I think you already have). Now this option I think would be more feasable. 

Also, currently, Bactopia doesn't support multiple species datasets due to the datasets being imported and runtime. So that is something I would need to tweak.

Would love to get your thoughts on this. I think, this would be a substantial enough change to the main Bactopia workflow that it would warrant a v1.5.0. Would you be will to test these features out before they arrive to Bioconda?

Thanks @embatty and @uloeber for the great feedback! It has been very helpful!

**Comment by uloeber** [comment]
Dear @rpetit3 ,
Thanks a lot! I will try that out and give you some more feedback. Again, you are doing an amazing job! Thank you.

**Comment by rpetit3** [comment]
Thank you very much! I'll update when it's been implemented

**Comment by embatty** [comment]
Hi @rpetit3 ,

Yes, that's the file arrangement I was thinking of. I do think it would be tricky to implement in the `bactopia prepare` step, because my filenames don't neatly fit the format (it's more like `laneA_barcode_1.fq,laneB_barcode_1.fq`), so it is neater to include at the `gather_fastq` stage. It's a nice to have feature rather than a key issue for me, if that helps prioritise when you take time to implementing it! I'm generally only running one species at a time, so I'm not sure what's the best way to add multiple species support.

**Comment by uloeber** [comment]
Hi @rpetit3 ,
just to check back again. I would like to assemble multiple samples and annotate them in one run. gather_fastq will just run multiple instances on bactopia on different samples, right? I have multiple copies of the same isolate and would like to merge them in one run. This means I would even need to give multiple paired fastqs for one "sample". Is this possible?
Best,
Ulrike

**Comment by rpetit3** [comment]
At the moment, you will need to merge the fastqs manually, then run Bactopia with the merged samples.

In the near future, the `gather_fastqs` step will do the merging for you.

**Comment by kusandeep** [comment]
Hi @rpetit3,
 I am having a similar issue where I have two R1 and two R2 files/samples. So should Just put both R1 in one cell R2 in next? sorry If I just wanted to double check before I get going.. see my FOFN file

![image](https://user-images.githubusercontent.com/38409245/100804284-7b643880-3491-11eb-8036-d554e6c60de6.png)

**Comment by rpetit3** [comment]
Hi @kusandeep  and everyone else! Guess its about time I tackle this issue! 

Unfortunately at the moment, you will need to manually merge them then feed them to Bactopia.

I'll begin work on the method @embatty  suggested above. With here suggestion your above fofn would work with Bactopia and bactopia would merge the FASTQs for you.

I'll update soon,

**Comment by kusandeep** [comment]
Thanks @rpetit3. So you mean I just leave my fofn as it is and for example: Sample 32 even though it is in two lines, will produce one assembly etc.?

**Comment by rpetit3** [comment]
In the next version, yes. I'll add the ability to have Bactopia merge these FASTQS for you.

Unfortunately, at the moment, if you want to process them as one sample you will need to merge yourself (outside of Bactopia), or make the sample names unique and process them as "2 samples" (which they are not).

**Comment by kusandeep** [comment]
@rpetit3 Thanks. Yes, make sense now.
Sorry, I deleted the query.

**Comment by rpetit3** [comment]
Good news everyone! I have an update. I've implemented this into Bactopia. It will only work if you are using a FOFN (`--fastqs`) created by `bactopia prepare` or yourself.

I've added three new `run_types`: `merge-pe`, `hybrid-merge-pe` and `merge-se`

In an FOFN it would look something like this:
```
sample	runtype	r1	r2	extra
sample_1	merge-pe	/path/001/sample_1_R1.fastq.gz,/path/002/sample_1.140_R1.fastq.gz	/path/001/sample_1_R2.fastq.gz,/path/002/sample_1_R2.fastq.gz	
sample_2	merge-se	/path/001/sample_1.fastq.gz,/path/002/sample_2.fastq.gz,/path/003/sample_2.fastq.gz,/path/004/sample_2.fastq.gz
```

I've maintained "all samples must be unique" in the FOFN, but have made it to where the `r1` and `r2` columns can have multiple comma-delimited FASTQs. Bactopia will recognize this and automatically merge the multiple read sets by concatenating the reads. 

When Bactopia recognizes samples with multiple read sets are used, a warning message is produced:
```
WARN: One or more samples consists of multiple read sets and will have their reads merged.
WARN: This is an experimental feature, please use with caution.
```

Samples that have multiple read sets merged, will also have a file called `multiple-read-sets-merged.txt` created. This is to let you know multiple runs were merged and also a basic sanity check. 

Here's a real example (paired end):
```
This sample had reads merged.
R1:
219468644	/local/home/rpetit/test/merged/2018-12-13/MRSABB_00130.140_R1.fastq.gz
103074654	/local/home/rpetit/test/merged/2018-12-03/MRSABB_00130.140_R1.fastq.gz
Merged R1:
322543298	fastqs/MRSABB_00130.140_R1.fastq.gz
R2:
215931317	/local/home/rpetit/test/merged/2018-12-13/MRSABB_00130.140_R2.fastq.gz
100656493	/local/home/rpetit/test/merged/2018-12-03/MRSABB_00130.140_R2.fastq.gz
Merged R2:
316587810	fastqs/MRSABB_00130.140_R2.fastq.gz
```
The numeric value is the file size reported by `ls -l` and the order in which the originals appear, is the order in which they are merged. 

The merge function looks like this:
```
# Paired-end
find -name "*r1" | sort | xargs -I {} readlink {} | xargs -I {} cat {} > fastqs/!{sample}_R1.fastq.gz
find -name "*r2" | sort | xargs -I {} readlink {} | xargs -I {} cat {} > fastqs/!{sample}_R2.fastq.gz

# Single-end (they stage with r1 ending)
find -name "*r1" | sort | xargs -I {} readlink {} | xargs -I {} cat {} > fastqs/!{sample}.fastq.gz
```
The goal with using `sort`, was so that the order is the same for R1/R2 pairs and they don't get out of order.

So for the above, it would be equivalent to this:
```
cat /local/home/rpetit/test/merged/2018-12-13/MRSABB_00130.140_R1.fastq.gz /local/home/rpetit/test/merged/2018-12-03/MRSABB_00130.140_R1.fastq.gz > fastqs/MRSABB_00130.140_R1.fastq.gz

cat /local/home/rpetit/test/merged/2018-12-13/MRSABB_00130.140_R2.fastq.gz /local/home/rpetit/test/merged/2018-12-03/MRSABB_00130.140_R2.fastq.gz > fastqs/MRSABB_00130.140_R2.fastq.gz
```

Here's another example for single-end sets:
```
This sample had reads merged.
SE:
215931317	/local/home/rpetit/test/merged/2018-12-13/MRSABB_00130.140_R2.fastq.gz
100656493	/local/home/rpetit/test/merged/2018-12-03/MRSABB_00130.140_R2.fastq.gz
219468644	/local/home/rpetit/test/merged/2018-12-13/MRSABB_00130.140_R1.fastq.gz
103074654	/local/home/rpetit/test/merged/2018-12-03/MRSABB_00130.140_R1.fastq.gz
Merged SE:
639131108	fastqs/MRSABB_00130.140-se.fastq.gz
```

This is an experimental function and is likely to have some bugs pop up. Please make sure that if you use this, to validate the `multiple-read-sets-merged.txt` file to make sure the orders are correct. I will likely build this check into the `bactopia summary`.

I will put this into the next version.

Thank you very much everyone for this very valuable suggestion!

**Comment by uloeber** [comment]
Dear Robert,This is great. Thanks a lot for this solution.Best wishes,Ulrike

Gesendet von Yahoo Mail auf Android 
 
  Am Sa., Dez. 5, 2020 at 2:23 schrieb Robert A. Petit III<notifications@github.com>:   


Good news everyone! I have an update. I've implemented this into Bactopia. It will only work if you are using a FOFN (--fastqs) created by bactopia prepare or yourself.

I've added three new run_types: merge-pe, hybrid-merge-pe and merge-se

In an FOFN it would look something like this:
sample	runtype	r1	r2	extra
sample_1	merge-pe	/path/001/sample_1_R1.fastq.gz,/path/002/sample_1.140_R1.fastq.gz	/path/001/sample_1_R2.fastq.gz,/path/002/sample_1_R2.fastq.gz	
sample_2	merge-se	/path/001/sample_1.fastq.gz,/path/002/sample_2.fastq.gz,/path/003/sample_2.fastq.gz,/path/004/sample_2.fastq.gz

I've maintained "all samples must be unique" in the FOFN, but have made it to where the r1 and r2 columns can have multiple comma-delimited FASTQs. Bactopia will recognize this and automatically merge the multiple read sets by concatenating the reads.

When Bactopia recognizes samples with multiple read sets are used, a warning message is produced:
WARN: One or more samples consists of multiple read sets and will have their reads merged.
WARN: This is an experimental feature, please use with caution.

Samples that have multiple read sets merged, will also have a file called multiple-read-sets-merged.txt created. This is to let you know multiple runs were merged and also a basic sanity check.

Here's a real example (paired end):
This sample had reads merged.
R1:
219468644	/local/home/rpetit/test/merged/2018-12-13/MRSABB_00130.140_R1.fastq.gz
103074654	/local/home/rpetit/test/merged/2018-12-03/MRSABB_00130.140_R1.fastq.gz
Merged R1:
322543298	fastqs/MRSABB_00130.140_R1.fastq.gz
R2:
215931317	/local/home/rpetit/test/merged/2018-12-13/MRSABB_00130.140_R2.fastq.gz
100656493	/local/home/rpetit/test/merged/2018-12-03/MRSABB_00130.140_R2.fastq.gz
Merged R2:
316587810	fastqs/MRSABB_00130.140_R2.fastq.gz

The numeric value is the file size reported by ls -l and the order in which the originals appear, is the order in which they are merged.

The merge function looks like this:
# Paired-end
find -name "*r1" | sort | xargs -I {} readlink {} | xargs -I {} cat {} > fastqs/!{sample}_R1.fastq.gz
find -name "*r2" | sort | xargs -I {} readlink {} | xargs -I {} cat {} > fastqs/!{sample}_R2.fastq.gz

# Single-end (they stage with r1 ending)
find -name "*r1" | sort | xargs -I {} readlink {} | xargs -I {} cat {} > fastqs/!{sample}.fastq.gz

The goal with using sort, was so that the order is the same for R1/R2 pairs and they don't get out of order.

So for the above, it would be equivalent to this:
cat /local/home/rpetit/test/merged/2018-12-13/MRSABB_00130.140_R1.fastq.gz /local/home/rpetit/test/merged/2018-12-03/MRSABB_00130.140_R1.fastq.gz > fastqs/MRSABB_00130.140_R1.fastq.gz

cat /local/home/rpetit/test/merged/2018-12-13/MRSABB_00130.140_R2.fastq.gz /local/home/rpetit/test/merged/2018-12-03/MRSABB_00130.140_R2.fastq.gz > fastqs/MRSABB_00130.140_R2.fastq.gz

Here's another example for single-end sets:
This sample had reads merged.
SE:
215931317	/local/home/rpetit/test/merged/2018-12-13/MRSABB_00130.140_R2.fastq.gz
100656493	/local/home/rpetit/test/merged/2018-12-03/MRSABB_00130.140_R2.fastq.gz
219468644	/local/home/rpetit/test/merged/2018-12-13/MRSABB_00130.140_R1.fastq.gz
103074654	/local/home/rpetit/test/merged/2018-12-03/MRSABB_00130.140_R1.fastq.gz
Merged SE:
639131108	fastqs/MRSABB_00130.140-se.fastq.gz

This is an experimental function and is likely to have some bugs pop up. Please make sure that if you use this, to validate the multiple-read-sets-merged.txt file to make sure the orders are correct. I will likely build this check into the bactopia summary.

I will put this into the next version.

Thank you very much everyone for this very valuable suggestion!

**Comment by rpetit3** [comment]
I'm going to go ahead and close this, please feel free to reopen if there are any problems.
