### ISSUE TITLE
[question] Troubleshooting failed steps? (annotate_genome, specifically)

### ISSUE THREAD

**Issue by tanaes** [bactopia/bactopia#122]
Making my way through my first test run, and I'm encountering a problem where none of the `annotate_genome` processes are succeeding. There's a brief message piped to the screen saying that the process failed, but I can't seem to find any log output with the STDERR from the process itself that might help identify what's going on. 

Any tips or suggestions?

**Comment by rpetit3** [comment]
Hmmm. Does the `.nextflow.log` file have any useful info in it?

**Comment by tanaes** [comment]
It doesn't, but this time the pipeline exited and I found this dumped to the screen:

```
...
  [10:48:44] Loading and checking input file: 11522_11845_115462_H3HCVAFX2_WC-19_CAGAACTG_TGGTTCGA.fna
  [10:48:44] Changing illegal '|' to '_' in sequence name: gnl|contig00001|11522_11845_115462_H3HCVAFX2_WC-19_CAGAACTG_TGGTTCGA
  [10:48:44] Contig ID must <= 37 chars long: gnl|Bactopia|11522_11845_115462_H3HCVAFX2_WC-19_CAGAACTG_TGGTTCGA_1
  [10:48:44] Please rename your contigs OR try '--centre X --compliant' to generate clean contig names
```

So it looks like the problem is with Prokka choking on the long contig names. (See for example [this note](https://darlinglab.org/tutorials/annotate/).)

**Comment by tanaes** [comment]
Rerunning with the `--compliant` tag to see if this fixes things. 

In my Snakemake workflows, I usually create a log file for each tool as it's executing, and dump STDERR to that log file. Is it possible to do something like that in Bactopia?

**Comment by rpetit3** [comment]
Yes to the logs. I'll get it added back in.

**Comment by rpetit3** [comment]
Update on the logs.

Here's what I've done. For each sample, a *logs* folder is generated. Inside the *logs* folder is a folder for each process (`assemble_genome`, `qc_reads`, etc...) executed by Nextflow. 

Here's an example:
```
logs/
├── ${PROCESS_NAME}/
│   ├── ${PROCESS_NAME}.err
│   ├── ${PROCESS_NAME}.out
│   ├── ${PROCESS_NAME}.run
│   ├── ${PROCESS_NAME}.sh
│   ├── ${PROCESS_NAME}.trace
│   └── ${PROCESS_NAME}.versions
└── ${PROCESS_NAME}/
    ├── ${PROCESS_NAME}.err
    ├── ${PROCESS_NAME}.out
    ├── ${PROCESS_NAME}.run
    ├── ${PROCESS_NAME}.sh
    ├── ${PROCESS_NAME}.trace
    ├── ${PROCESS_NAME}.versions
    ├── ${PROGRAM}.err
    ├── ${PROGRAM}.log
    └── ${PROGRAM}.out
```

Each folder will have the `${PROCESS_NAME}.{err,out,run,sh,trace,versions}` files, which are copies of Nextflow's `.command` files, with exception to `.versions` which contains version numbers for programs *directly* executed (e.g. Prokka but not tbl2asn which is executed within Prokka)

For certain programs, there can be `${PROGRAM}.{err,log,out}`. Not all processes get this treatment, for example `count_31mers` only executes mccortex so `${PROCESS_NAME}.{exts}` I thought was enough.

One thing to mention, the `${PROCESS_NAME}` files are copied at the end of the process. The `${PROGRAM}` files are at runtime,  (`prokka 1> prokka.out 2> prokka.err`) and since STDOUT/STDERR is captured, Nextflow won't display it there is an error. Instead your error message above would be in the prokka.err file.

Another thing, these files are not moved into the sample folder until the process completed successfully. In cases where there's an error, you will still have to find the logs in the `work` directory.

I'll document this more, but wanted to get your thoughts on whether this would meet your needs. 

Thank you very mush for your feedback, it has been really helpful!

**Comment by rpetit3** [comment]
Hi @tanaes 

Me again! Going to close this issue, please feel free to reopen if the need arises!

Thank you very much for the feedback!
Robert
