### ISSUE TITLE
[feature] Coverage output

### ISSUE THREAD

**Issue by marcelladane** [bactopia/bactopia#164]
Hello, me again. =)

Does bactopia output the coverage of the sequence anywhere? 
What I mean is, after assembly, does the assembler already compute the average coverage across all nucleotides in the genome and have this output anywhere?

I know that bbmap's pileup functions do it. But I can't find the info on my output files. And it's important to have at least a 30x coverage of the sequence to be confident in the results. Right?

**Comment by rpetit3** [comment]
Hi @marcelladane!

Let's see, there are estimated coverages for the FASTQs (https://bactopia.github.io/output-overview/#quality-control) in the `*.json` files.

```
${SAMPLE_NAME}/
└── quality-control
    └── summary-(original|final)
        └── ${SAMPLE_NAME}(|_R1|_R2)-(original|final).json
```

As for assemblies, there isn't a "per-base" coverage but it does give a "per-contig" estimated coverage. This should be available in the contig header as `cov=00.0`, here are examples:

```
>gnl|contig00001|DRX014040 len=188015 cov=75.7 corr=0 origname=Contig_76_75.6776_pilon sw=shovill-skesa/1.1.0 date=20201020
>gnl|contig00002|DRX014040 len=173731 cov=80.7 corr=0 origname=Contig_12_80.7102_pilon sw=shovill-skesa/1.1.0 date=20201020
>gnl|contig00003|DRX014040 len=155810 cov=80.0 corr=0 origname=Contig_81_80.0422_pilon sw=shovill-skesa/1.1.0 date=20201020
>gnl|contig00004|DRX014040 len=150458 cov=79.1 corr=0 origname=Contig_4_79.124_pilon sw=shovill-skesa/1.1.0 date=20201020
>gnl|contig00005|DRX014040 len=138732 cov=74.0 corr=0 origname=Contig_75_73.9836_pilon sw=shovill-skesa/1.1.0 date=20201020
>gnl|contig00006|DRX014040 len=129360 cov=72.7 corr=0 origname=Contig_18_72.7319_pilon sw=shovill-skesa/1.1.0 date=20201020
>gnl|contig00007|DRX014040 len=125393 cov=76.4 corr=0 origname=Contig_74_76.352_pilon sw=shovill-skesa/1.1.0 date=20201020
>gnl|contig00008|DRX014040 len=109478 cov=74.7 corr=0 origname=Contig_65_74.6735_pilon sw=shovill-skesa/1.1.0 date=20201020
>gnl|contig00009|DRX014040 len=108065 cov=79.8 corr=0 origname=Contig_34_79.7518_pilon sw=shovill-skesa/1.1.0 date=20201020
>gnl|contig00010|DRX014040 len=106855 cov=77.2 corr=0 origname=Contig_38_77.1773_pilon sw=shovill-skesa/1.1.0 date=20201020
```

By default Bactopia only removes contigs with less than 2x coverage which is the [default used by Shovill](https://github.com/tseemann/shovill/blob/master/bin/shovill#L700). So yes, I think its definitely worth filtering your results based on contig coverage. 

Haha for your final question, is 30x coverage good enough? That's a hard one to answer because its no study specific, but I think 30x is definitely safe. 

Does this help?

**Comment by marcelladane** [comment]
Absolutely. Thank you.

Have a nice weekend

**Comment by rpetit3** [comment]
you too!
