### ISSUE TITLE
[question] Bactopia vs Shovill assembly differences

### ISSUE THREAD

**Issue by maesaar** [bactopia/bactopia#179]
I was wondering why are the bactopia and shovill assemblies quite different?

Bactopia command:
`bactopia --R1 Desktop/CAMP_UT/shovill/CAMP176_S56_R1.fastq.gz --R2 Desktop/CAMP_UT/shovill/CAMP176_S56_R2.fastq.gz --datasets datasets/ --species "Campylobacter jejuni" --coverage 100 --genome_size median --cpus 4 --max_memory 58 --shovill_ram 58 --trim --sample CAMP176_S56 --outdir jejuni`

Bactopia shovill output example:
`[shovill] It contains 115 (min=500) contigs totalling 1716672 bp.`

Shovill command:
`shovill --R1 CAMP176_S56_R1.fastq.gz --R2 CAMP176_S56_R2.fastq.gz --outdir CAMP176_S56_skesa --keepfiles --minlen 200 --ram 58 --trim --assembler skesa`

Shovill output example:
`[shovill] It contains 71 (min=200) contigs totalling 1728670 bp.`

Thank you @rpetit3

**Comment by rpetit3** [comment]
Hi @maesaar!

My first guess is because they are using two different inputs. In Bactopia Shovill uses trimmed/error corrected FASTQs and in Shovill alone the raw FASTQs are used. (At least that's what I'm thinking from example above.)

You could try `--skip_qc` which should pass the raw FASTQs to Shovill in Bactopia.

Just curious, what are assembly stats for the two? (N50 etc..)

**Comment by maesaar** [comment]
Hi again!

I was using shovill with --trim option so the shovill uses also trimmed FASTQs as input.

Shovill alone:
Contig Stats": {
    "L10": 1,
    "L20": 2,
    "L30": 4,
    "L40": 6,
    "L50": 8,
    "N10": 126987,
    "N20": 111367,
    "N30": 91648,
    "N40": 71081,
    "N50": 66186,
    "gc_content": 30.294619563016656,
    "longest": 153213,
    "mean": 24347.464788732395,
    "median": 9591.0,
    "sequence_count": 71,
    "shortest": 385,
    "total_bps": 1728670
  }

Bactopia:
"Contig Stats": {
    "L10": 1,
    "L20": 2,
    "L30": 5,
    "L40": 9,
    "L50": 15,
    "N10": 129075,
    "N20": 98918,
    "N30": 50883,
    "N40": 30412,
    "N50": 25255,
    "gc_content": 30.35046881407747,
    "longest": 137580,
    "mean": 14927.582608695651,
    "median": 9619.0,
    "sequence_count": 115,
    "shortest": 523,
    "total_bps": 1716672
  }

**Comment by rpetit3** [comment]
Shovill's `--trim` option is a little different, it only removes Illumina adapters.

For Bactopia there's a [Quality Control](https://bactopia.github.io/workflow-overview/#quality-control) step that cleans up FASTQs. This step uses BBTools and Lighter to remove adapters, trim reads based on quality, error-correct, then reduce to a given coverage (default 100x). These processed FASTQs are then used for the [Assembly](https://bactopia.github.io/workflow-overview/#de-novo-assembly) step with Shovill.



Going back to the commands above, Bactopia's Shovill looks something like this:
```
shovill --R1 PROCESSED_CAMP176_S56_R1.fastq.gz --R2 PROCESSED_CAMP176_S56_R2.fastq.gz --outdir CAMP176_S56_skesa --keepfiles --minlen 200 --ram 58 --trim --assembler skesa
```

and the Shovill is still this:
```
shovill --R1 CAMP176_S56_R1.fastq.gz --R2 CAMP176_S56_R2.fastq.gz --outdir CAMP176_S56_skesa --keepfiles --minlen 200 --ram 58 --trim --assembler skesa
```

For Bactopia, you can remove the `--trim` option unless you are also using `--skip_qc`.

The assemblies look similar, but I'd say the raw reads produced a "better" assembly. I wonder if its due to coverage reduction, or something from the clean up process.

**Comment by maesaar** [comment]
Raw reads you mean reads used and trimmed with shovill?

**Comment by rpetit3** [comment]
Yep. I guess better term be "original inputs"

Bactopia modifies your original inputs, making them different than had you used Shovill directly. The only way to make Shovill use the original inputs in Bactopia is to use `--skip_qc`. Otherwise, the two approaches are using different inputs (original FASTQ vs processed FASTQ), and different results are OK.

**Comment by maesaar** [comment]
Thank you for the clarification @rpetit3
