### ISSUE TITLE
[question]  Index 1 out of bounds for length 1 Error

### ISSUE THREAD

**Issue by andriesfeder** [bactopia/bactopia#193]
Hello!

I have been running into a problem with Call Variants Auto (everything else in Bactopia has been working for me).  I have been getting an index out of bounds error and am not sure why.  I have paste the execution summary below.

Any help would greatly appreciated!

Andries

        `  Bactopia Execution Summary
            ---------------------------
            Command Line    : nextflow run /Users/afeder/anaconda3/envs/bactopia//share/bactopia-1.6.x/main.nf -w /Volumes/LaCie_2/Bactopia/work/bactopia --R1 fastqs/S.191121.00364_R1.fastq.gz --R2 fastqs/S.191121.00364_R2.fastq.gz --sample S.191121.00364 --datasets /Users/afeder/Desktop/PJP/bactopia/datasets/ --species Staphylococcus aureus
            Resumed         : false
        
            Completed At    : 2021-02-17T11:05:38.770092-05:00
            Duration        : 4m 58s
            Success         : false
            Exit Code       : null
            Error Report    : Error executing process > call_variants_auto (S.191121.00364 - null)
        
        Caused by:
          Index 1 out of bounds for length 1
        
        Source block:
          snippy_ram = task.memory.toString().split(' ')[0]
          reference_name = reference.getSimpleName().split("${sample}-")[1].split(/\./)[0]
          fastq = single_end ? "--se ${fq[0]}" : "--R1 ${fq[0]} --R2 ${fq[1]}"
          bwaopt = params.bwaopt ? "--bwaopt 'params.bwaopt'" : ""
          fbopt = params.fbopt ? "--fbopt 'params.fbopt'" : ""
          template(task.ext.template) `

**Comment by rpetit3** [comment]
Looks like the issue is here:

```
reference_name = reference.getSimpleName().split("${sample}-")[1].split(/\./)[0]
```
Its returning `null` (`(S.191121.00364 - null)`) when it should be the reference name.

Was there more to the STDERR to work with? I'm curious if `download_references` downloaded anything, and if it did if there was something about its name that broke that one line.

Could you also post your dataset summary? Should be `/Users/afeder/Desktop/PJP/bactopia/datasets/sumamry.json`

**Comment by andriesfeder** [comment]
Thanks for the quick response! There was nothing else I was getting.  It looked like `download_references` completed successfully with one reference downloaded.


[summary.json.zip](https://github.com/bactopia/bactopia/files/6003923/summary.json.zip)

**Comment by rpetit3** [comment]
Going to see if I can replicate this. I'm wondering if the sample name `S.191121.00364` might be causing the problem. 

Will update soon

**Comment by rpetit3** [comment]
Good news! I'm getting the error too!
```
Error executing process > 'call_variants_auto (S.200218.00761 - null)'

Caused by:
  1

Source block:
  snippy_ram = task.memory.toString().split(' ')[0]
  reference_name = reference.getSimpleName().split("${sample}-")[1].split(/\./)[0]
  fastq = single_end ? "--se ${fq[0]}" : "--R1 ${fq[0]} --R2 ${fq[1]}"
  bwaopt = params.bwaopt ? "--bwaopt 'params.bwaopt'" : ""
  fbopt = params.fbopt ? "--fbopt 'params.fbopt'" : ""
  template(task.ext.template)

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
```

I'll get this fixed

**Comment by rpetit3** [comment]
Ok figured it out. I was using `.getSimpleName()` when I should have used `.getBaseName()`. Here's details from Nextflow docs


Name | Description
-- | --
getName | Gets the file name e.g. /some/path/file.txt -> file.txt
getBaseName | Gets the file name without its extension e.g. /some/path/file.tar.gz -> file.tar
getSimpleName | Gets the file name without any extension e.g. /some/path/file.tar.gz -> file


Becuase I used  `.getSimpleName()` the filename `S.200218.00761-GCF_000017085.gbk` became `S`, because `getSimpleName` removes all extensions (I'm guessing something like `"STRING".split('.')[0]`)

Where as `getBaseName()` will just remove the last extension, so `S.200218.00761-GCF_000017085.gbk` becomes  `S.200218.00761-GCF_000017085` like we want.

I've fixed this and will push it soon. In the mean time, if you don't need the auto variant calls you can use `--disable_auto_variants` to skip it.

**Comment by andriesfeder** [comment]
Sounds good! Thanks so much for your help!

**Comment by rpetit3** [comment]
@andriesfeder bactopia v1.6.1 has been released. 

This version should fix your problem, if not please feel free to reopen. 

Let me know if there's anything else I can help out with!

**Comment by shlomobl** [comment]
Hi all,
I'm having a similar error so I thought to post in the same thread.
I'm having this error after upgrading to bactopia 2.0 (previous version passed this stage fine)...

Error executing process > 'BACTOPIA:MINMER_QUERY (CAF75362 - genbank-k31)'

Caused by:
  **Index 2 out of bounds for length 2**

Source block:
  dataset_basename = dataset.getSimpleName()
  dataset_info = dataset_basename.split("-")
  program = dataset_info[0]
  database = dataset_info[1]
  kmer = dataset_info[2]
  mash_w = params.no_winner_take_all ? "" : "-w"
  fastq = meta.single_end ? "${fq[0]}" : "${fq[0]} ${fq[1]}"
  '''
      OUTPUT="!{meta.id}-!{program}-!{database}-!{kmer}.txt"
      OUTPUT_ERR="!{program}-!{database}-!{kmer}.stderr.txt"
      if [ "!{program}" == "mash" ]; then
          echo "identity<TAB>shared-hashes<TAB>median-multiplicity<TAB>p-value<TAB>query-ID<TAB>query-comment" | sed 's/<TAB>/\t/g' > ${OUTPUT}
          gzip -cd !{fastq} | \
              mash screen !{mash_w} -i !{params.screen_i} -p !{task.cpus} !{dataset} - | \
              sort -gr >> ${OUTPUT} 2> ${OUTPUT_ERR}
      elif [ "!{program}" == "sourmash" ]; then
          sourmash lca classify --query !{sourmash} --db !{dataset} > ${OUTPUT} 2> ${OUTPUT_ERR}
      fi
  
      # Capture versions
      cat <<-END_VERSIONS > versions.yml
      minmer_query:
          mash: $(echo $(mash --version 2>&1))
          sourmash: $(echo $(sourmash --version 2>&1) | sed 's/sourmash //;')
      END_VERSIONS
      '''

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

**Comment by shlomobl** [comment]
I can see a ".getSimpleName" there. Could be the same issue?

**Comment by chuanfaliu** [comment]
@shlomobl I have the same problem. I changed line 31 from `getSimpleName` to `getBaseName` in `bactopia/share/bactopia-2.0.x/modules/local/bactopia/minmer_query/main.nf`, but it didn't work.
