### ISSUE TITLE
Error executing process fastq_status

### ISSUE THREAD

**Issue by siwei-deng** [bactopia/bactopia#204]
Hi, 

I'm running Bactopia but always have errors when it starts processing. The error message is [here](https://github.com/bactopia/bactopia/files/6157180/error.txt). 

This is how I install and run: 
```
conda create -y -n bactopia -c conda-forge -c bioconda bactopia
conda activate bactopia
bactopia datasets
bactopia --R1 seq1.fastq --R2 seq2.fastq --datasets datasets/ --sample mysample --outdir ./
```

The Linux machine is Ubuntu 20.04. 

Thank you for any help!

**Comment by rpetit3** [comment]
Hi @siwei-deng! This looks like aduplicate of https://github.com/bactopia/bactopia/issues/203.

I'm going to get that fixed and push a new version today.

In the meantime, if don't think there are any issues with your input FASTQs, you can can use `--skip_fastq_check`.

**Comment by rpetit3** [comment]
Disregard the previous comment, this is different:

EDIT: This looks different
```
Command error:
  
  gzip: 1A1_R1.fastq.gz: not in gzip format
  .command.sh: line 48: 827394 Exit 1                  gzip -cd 1A1_R1.fastq.gz
       827395 Segmentation fault      (core dumped) | fastq-scan > r1.json
```

This is due to the input FASTQs not being compressed, when they are expected to be.

```
    --R1 STR                First set of reads for paired end in compressed (gzip)
                                FASTQ format

    --R2 STR                Second set of reads for paired end in compressed (gzip)
                                FASTQ format
```

The easiest would be to compress your FASTQs

However, I think being able to start analysis with incorrect inputs is a bug that I should fix. So, I'm going correct this and either force a check before starting analysis or just allow uncompressed FASTQs.

**Comment by siwei-deng** [comment]
Thanks for @rpetit3 comments! That's all fixed!
