### ISSUE TITLE
[bug] bactopia v 1.7.0 gtdbtk v 1.5.0

### ISSUE THREAD

**Issue by uloeber** [bactopia/bactopia#216]
Hi @rpetit3 ,
It seems that updating bactopia to v 1.7.0 triggers a downgrade of gtdbtk

`conda install -c bioconda bactopia==1.7.0`
`gtdbtk                                 1.5.0-pyhdfd78af_0 --> 1.0.2-py_2`

while updating gtdbtk to v 1.5.0 triggers a bactopia downgrade

`conda install -c bioconda gtdbtk==1.5.0 `
`bactopia                                 1.7.0-hdfd78af_0 --> 1.5.6-0`

gtdbtk 1.5.0 is necessary for the latest gtdb release 202. Just wanted to report that. might be a bug 

Best,
Ulrike

**Comment by rpetit3** [comment]
Hi @uloeber! Hope all is well for you!

I think it might be best to use the Bactopia Tool for GTDB (`bactopia tools gtdb`) since it won't create conflicts.

But looking at that I will need to push the GTDB version from 1.4.0 to 1.5.0 on the bactopia tool. I'll get that put into 1.7.1 and push it soon.

Also heads up, I'm probably going to start recommending to use [Mamba](https://github.com/mamba-org/mamba) to install bactopia from conda. I've noticed its starting to take 10+ minutes to create and solve the environment, whereas mamba is a few seconds.

**Comment by uloeber** [comment]
Dear @rpetit3 ,
Ah, okay, I was not aware that I installed gtdbtk alongside. I intended to use it via bactopia tools and thought there are versioning conflicts. Yes, pushing it in the next version would be great, thanks!
Best,
Ulrike

**Comment by rpetit3** [comment]
Hi @uloeber,

I'm available to start working on this, and will get an update pushed soon.

Robert

**Comment by uloeber** [comment]
Hi @rpetit3 ,
this would be great! Thank you so much!
Ulrike

**Comment by rpetit3** [comment]
Hi @uloeber 

v1.5.0 of GTDB should be available in the newest version of Bactopia v1.7.1 (https://github.com/bactopia/bactopia/releases/tag/v1.7.1).

Please let me know if there are any issues.

Thank you! 
Robert
