### ISSUE TITLE
Summary doc for all genomes

### ISSUE THREAD

**Issue by brross60** [bactopia/bactopia#277]
Is there a way to pull the basic stats for all genomes after assembly or annotation? I have ~60 genomes that I ran all at once and it is a lot to go in and out of each folder to pull assembly stats (length, contigs, GC%, etc).

**Comment by rpetit3** [comment]
Hi @brross60,

I'm hoping to bring that back in the next version. If you have any ideas or suggestions please feel free to share!

Robert

**Comment by jellyvanderwoude** [comment]
I second this idea! I have 300 samples and it's difficult to go into each folder manually to parse out information. I would love MLST typing to also be included in such a "basic stats" folder. Also for batches of samples that are called against the same reference strain, if there's a way to combine the vcf/ snp calling outputs in some way (not sure if this is outside the scope of Bactopia) so that I can easily compare SNPs across various closely related strains that I'm running through Bactopia.

Love seeing this tool improve and grow!

**Comment by rpetit3** [comment]
Hello! I've released v2.0.2 (https://github.com/bactopia/bactopia/releases/tag/v2.0.2), in the next version I'm going to focus on being able to generate reports! 


@jellyvanderwoude thanks for the kind words and motivation!

**Comment by rpetit3** [comment]
Hi @brross60 

I brought back the `bactopia summary` in v3. Since I'm cleaning up old issues and this is related to v2, I'm going to go ahead and close this with the recommendation to give v3 a try.

Please reach out if you have any questions or issues!

Cheers,
Robert
