### ISSUE TITLE
[bug] bactopia datasets AMRFinder+

### ISSUE THREAD

**Issue by MRMHmdeleeuw** [bactopia/bactopia#377]
**Description**
Thank you very much for providing Bactopia. After upgrading to bactopia 2.2.0, `bactopia datasets` errors out on AMRFinder+ DB installation. A patch to correct the glitch is provided below.

**Steps to Reproduce**
```
bactopia datasets
...
2022-12-04 10:16:00:root:INFO - Setting up latest AMRFinder+ database
External command failed with exit code 1!

Command:
bash -c 'mv 2022-10-11.2/* amrfinderdb/'

Standard error:
mv: cannot stat '2022-10-11.2/*': No such file or directory
```

**Expected Behavior**
Errorless datasets installation.

**Execution Environment**

- Bactopia Version: bactopia 2.2.0
- OS: Linux 5.15.79.1-microsoft-standard-WSL2 SMP Wed Nov 23 01:01:46 UTC 2022 x86_64 GNU/Linux
- OS: Linux 5.4.17-2136.305.5.4.el8uek.x86_64 SMP Mon Mar 28 19:05:22 PDT 2022 x86_64 GNU/Linux
- Environment: miniconda3

**Additional Information**
Patch bin/bactopia-datasets.py with the following diff to correct the problem:
```
608c608
<             execute(f'mv {latest_db}/* {prefix}/', directory=amr_dir)
---
>             execute(f'mv {prefix}-temp/{latest_db}/* {prefix}/', directory=amr_dir)
```
Now `bactopia datasets` runs as expected.
```
...
2022-12-04 10:25:32:root:INFO - Setting up latest AMRFinder+ database
2022-12-04 10:26:31:root:INFO - AMRFinder+ database saved to ./datasets/antimicrobial-resistance/amrfinderdb.tar.gz
2022-12-04 10:26:31:root:INFO - No requests for an species, skipping
2022-12-04 10:26:31:root:INFO - Writing summary of available datasets
```

**Comment by MRMHmdeleeuw** [comment]
Hi, I saw this was fixed in the dev branch already, just needs to be merged.

**Comment by rpetit3** [comment]
Hi @MRMHmdeleeuw 

Thank you for bringing this up. Haha looks like it wasn't just you! https://github.com/bactopia/bactopia/issues/373

If you want, I have a conda build for my dev branch:
```
mamba create -n bactopia-dev -c rpetit3 -c conda-forge -c bioconda bactopia
```

Looks like I'll probably be pushing a patch soon though since libgsl is also causing problems

Cheers,
Robert

**Comment by MRMHmdeleeuw** [comment]
Thank you Robert, good to know there is a dev Conda package for Bactopia because we wanted to use the latest Bakta as well. Best regards.

**Comment by lfenske-93** [comment]
Hi Robert,

I'm a little bit stuck, but unfortunately I get the same error even if I use the dev-build... 🤔 

Any idea what the problem might be?

Greetings,
Linda

**Comment by rpetit3** [comment]
Oh, that is unexpected. Let me look into this

**Comment by mmcguffi** [comment]
Hi @rpetit3,

Unfortunately the debug branch from your conda channel isn't working for me either. This is the error I get after running `bactopia datasets` (+/- `--outdir datasets`):

```bash
2022-12-18 15:33:55:root:INFO - Setting up pre-computed Genbank/Refseq minmer datasets
2022-12-18 15:34:21:root:INFO - Setting up antimicrobial resistance datasets
2022-12-18 15:34:21:root:INFO - Setting up latest AMRFinder+ database
External command failed with exit code 1!

Command:
bash -c 'mv amrfinderdb-temp//{my_path}/datasets/antimicrobial-resistance/amrfinderdb-temp/2022-10-11.2/* amrfinderdb/'

Standard error:
mv: cannot stat 'amrfinderdb-temp//{my_path}/datasets/antimicrobial-resistance/amrfinderdb-temp/2022-10-11.2/*': No such file or directory
```

I assume this is because of the `//` in the path? And/or perhaps this is because `{my_path}` above is actually my home directory path? I removed it for privacy, but you can imagine it's something like `mcg/projects/project_1`. Maybe this is the intended behavior of where `amrfinderdb-temp` is supposed to be created, but Im on a cluster can see how this might mess with things

Any help or tips would be appreciated :)

**Comment by lfenske-93** [comment]
Any news? I still have the problems with the dev-build too, unfortunately. 😕 

```
(bactopia-dev) lfenske@hp-dl560:/vol/gbs_lhl/bactopia$ bactopia datasets
2023-01-17 11:32:26:root:INFO - Setting up pre-computed Genbank/Refseq minmer datasets
2023-01-17 11:32:26:root:INFO - ./datasets/minmer/sourmash-genbank-k21.json.gz exists, skipping
2023-01-17 11:32:26:root:INFO - ./datasets/minmer/sourmash-genbank-k31.json.gz exists, skipping
2023-01-17 11:32:26:root:INFO - ./datasets/minmer/sourmash-genbank-k51.json.gz exists, skipping
2023-01-17 11:32:26:root:INFO - ./datasets/minmer/mash-refseq-k21.msh exists, skipping
2023-01-17 11:32:26:root:INFO - Setting up antimicrobial resistance datasets
2023-01-17 11:32:26:root:INFO - Setting up latest AMRFinder+ database
External command failed with exit code 1!

Command:
bash -c 'mv 2022-10-11.2/* amrfinderdb/'

Standard error:
mv: cannot stat '2022-10-11.2/*': No such file or directory
```

**Comment by rpetit3** [comment]
Hi @lfenske-93,

As a temporary, keep you moving measure, you can download this file: https://datasets.bactopia.com/datasets/v2.2.0/amrfinderdb.tar.gz

Then put it in `./datasets/antimicrobial-resistance` folder.

I'm making some changes in the next version, which will be removing the need to rebuild some of these databases. 

Let me know if this doesn't work for you!
Robert

**Comment by uloeber** [comment]
Hi Robert,
hope you are doing well. I kind of have the same problem and tried your fix already. All data should be there (trying to fix the bug by downloading the data seperatelty). I ignored the warning "WARNING: A newer version of the database exists (2022-12-19.1), but it requires a newer version of the software (3.11) to install.
See https://github.com/ncbi/amr/wiki/Upgrading for more information.


WARNING: '/home/uloeber/bactopia-20201013/anaconda3/envs/bactopia_2023/share/amrfinderplus/data/2022-10-11.2/' contains the latest version: 2022-10-11.2
Skipping update, use amrfinder --force_update to overwrite the existing database" since I saw that bactopia is using the older amrfinder version, is that correct?

```
amrfinderdb/AMR_DNA-Clostridioides_difficile.nin
amrfinderdb/AMR_DNA-Escherichia.njs
amrfinderdb/AMR_DNA-Enterococcus_faecalis.ntf
amrfinderdb/AMR_CDS.ntf
```

```
(bactopia_2023) bactopia datasets
2023-02-11 09:21:02:root:INFO - Setting up pre-computed Genbank/Refseq minmer datasets
2023-02-11 09:21:02:root:INFO - ./datasets/minmer/sourmash-genbank-k21.json.gz exists, skipping
2023-02-11 09:21:02:root:INFO - ./datasets/minmer/sourmash-genbank-k31.json.gz exists, skipping
2023-02-11 09:21:02:root:INFO - ./datasets/minmer/sourmash-genbank-k51.json.gz exists, skipping
2023-02-11 09:21:02:root:INFO - ./datasets/minmer/mash-refseq-k21.msh exists, skipping
2023-02-11 09:21:02:root:INFO - Setting up antimicrobial resistance datasets
2023-02-11 09:21:02:root:INFO - Setting up latest AMRFinder+ database
External command failed with exit code 1!

Command:
bash -c 'mv 2022-10-11.2/* amrfinderdb/'

Standard error:
mv: cannot stat '2022-10-11.2/*': No such file or directory```

**Comment by rpetit3** [comment]
hi all! Super close on next version, which will make thing like this much easier.

Hi @uloeber! For the bactopia v2.2.0 is on AMRFinder+ 3.10.45. New version will be on the latest AMRFinder+.

Did you run `bactopia datasets` with `--skip_amr`? Then manually put the [tarball](https://datasets.bactopia.com/datasets/v2.2.0/amrfinderdb.tar.gz) into the `./datasets/antimicrobial-resistance` folder?

**Comment by uloeber** [comment]
Thank you so much for your quick response! I deleted all data and ran it again with --skip_amr and looks like it works now. Thanks again

**Comment by incoherentian** [comment]
> External command failed with exit code 1!
>
> Command:
> bash -c 'mv 2022-10-11.2/* amrfinderdb/'

I had the same issue trying to mamba 2.2.0 today. The `--skip_amr` modification...

> `bactopia datasets` with `--skip_amr`

...let 2.2.0 carry on to the "Writing summary of available datasets" stage and finish :) Still working out the parameters to actually get BACTOPIA:ANTIMICROBIAL_RESISTANCE going, but the other basics are working. TY both!

I also tried the dev release which seemed to get stuck here:
```
(base) wslmedib:/mnt/c/wsl/20230214-dragonflyepoly$ conda activate bactopia-dev20230218
(bactopia-dev20230218) wslmedib:/mnt/c/wsl/20230214-dragonflyepoly$ bactopia datasets
2023-02-18 17:15:17:root:INFO - Checking if environment pre-builds are needed, use --verbose to see full details.
2023-02-18 17:15:17:root:INFO - Begin gather create to /home/wslmedib/conda/mamba/envs/bactopia-dev20230218/share/bactopia-2.2.x/conda/envs/conda_tools------bioconda--bactopia-gather-1.0.1
```
(also getting stuck if I `--skip_amr` for the dev release dataset building)

Or maybe not actually stuck and I should expect it to take several times longer than the non-dev?

**Comment by jelmerp** [comment]
Not sure if you still want to make any changes to Bactopia v2, @rpetit3, but this bug does have an easy fix as far as I can tell.

**Underlying problem in the code**

The `bactopia-datasets.py` script has the following on lines 607-608:

```python
latest_db = os.readlink(f'{amr_dir}/{prefix}-temp/latest')
execute(f'mv {latest_db}/* {prefix}/', directory=amr_dir) 
```

The problem is that `os.readlink` just returns the basename of the directory (in this case, `2022-10-11.2`) -- as a result, `mv` doesn't get told this file is in fact in the `{prefix}-temp` directory within `amr_dir`.

**Proposed solution**

Tell `mv` about the `{prefix}-temp` dir by changing line 608 to:
 
```python
execute(f'mv {prefix}-temp/{latest_db}/* {prefix}/', directory=amr_dir)
```

I tested this and it worked.

Thanks!

**Comment by crabhi** [comment]
I can confirm this change works. Thanks.

**Comment by rpetit3** [comment]
Hi everyone here!

I'm happy to report I have [released version 3 of Bactopia](https://github.com/bactopia/bactopia/releases/tag/v3.0.0). This is now no longer an issue (hooray!). V3 now comes with a version locked amrfinder+ database, so that updates in AMRFinder+ don't affect previous Bactopia versions (v3+) 

Thanks for using Bactopia!
Robert
