### ISSUE TITLE
[bug] art_illumina: error while loading shared libraries: libgsl.so.25

### ISSUE THREAD

**Issue by lfenske-93** [bactopia/bactopia#388]
Hi Robert, 

I try using Bactopia for a bunch of assemblies but run into a error already at the beginning...

```
Command exit status:
  127

Command output:
  (empty)

Command error:
  art_illumina: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory

Work dir:
  /vol/gbs_lhl/bactopia/work/66/a53d09a6790a2c4157ccd7ba2a2d1e
```

Is this a problem I can somehow solve myself?

Many thanks for your help.
Greetings,
Linda

**Comment by rpetit3** [comment]
Hi @lfenske-93 

Let's get this fix! Are you using conda, docker or singularity?

Cheers,
Robert

**Comment by lfenske-93** [comment]
I'm using conda.

**Comment by rpetit3** [comment]
Cool, this might be the easiest to try first. The issue is with the v2.7 build of GSL and downgrading to v2.6 is usually the fix.

Let's try 
```
conda activate /path/to/your/gather-samples-env/
conda install -c conda-forge -c bioconda 'gsl=2.6'
```

If it's hard to find the path to the conda environment, I think it usually appears in the output of `conda env list` 

Unfortunately, there might be other envs affected by this.

**Comment by lfenske-93** [comment]
Okay, took me a while to find the environment 😄 

 But seems to work though, let's see the error occurs again elsewhere.
 
Thanks for the quick help! 😄

**Comment by rpetit3** [comment]
Hi @lfenske-93 

Me again! v3 is now out.

Again, thank you so much for all your help!
Robert
