### ISSUE TITLE
pneumoCat added to strep pneumo merlin workflow

### ISSUE THREAD

**Issue by flashton2003** [bactopia/bactopia#406]
Hi Robert,

I would like to request that pneumoCat, or a similar tool, is added to the Strep pneumo merlin workflow.

https://github.com/ukhsa-collaboration/PneumoCaT

Thanks!

Phil

**Comment by rpetit3** [comment]
Hi Phil, 

Sure, why not? I'll try to get it into the v3 release, otherwise into a near future release.

Cheers,
Robert

**Comment by flashton2003** [comment]
Great, thank you!

**Comment by PHemarajata** [comment]
Hi @flashton2003 . Is there a reason you prefer that over seroba?

**Comment by flashton2003** [comment]
Nope, either is fine.

**Comment by rpetit3** [comment]
@flashton2003  I've added PneumoCAT to v3 (still need to add to merlin)

I will warn you, it has not aged well. A few things I ran into while running it

1. `--fastq_1` and `--fastq_2` cannot be used because `--input_directory` is never set causing issues downstream when trying to using `input_directory`
2. Because `--input_directory` is used, a glob is used that only matches `*fastq*` (which should be ok for Bactopia), but it randomly based on which one glob finds first sets the prefix to `SAMPLE_R1` or `SAMPLE_R2`
3. The outputs are in XML, so there will not be a merged report
4. Instead of allowing a negative result, non Strep pneumo samples fail spectacularly

I think there is a strong need to make some quality of life improvements to PneumoCAT (e.g. TSV output and allowing a negative result), but I'm not sure PneumoCAT is supported any more.

I wonder if [PenumoKITy](https://github.com/CarmenSheppard/PneumoKITy) might be a better alternative, not sure whether it's still supported, but at least newer and addresses some my concerns

**Comment by PHemarajata** [comment]
I have used standalone seroba with pneumocat database without any issue.
Seroba on bactopia or Terra also works. I personally don’t need another
tool for strep pneumo but others may prefer other tools.

P

**Comment by flashton2003** [comment]
seroba with the pneumocat database would be fine for us! Sorry, didn’t
realise pneumocat is no longer supported.

**Comment by rpetit3** [comment]
Hi @flashton2003 and @PHemarajata 

I've release v3, which includes pneumocat now. 

Thank you both for your feedback and ideas!
Robert

**Comment by flashton2003** [comment]
Thanks Robert!
