### ISSUE TITLE
Hybrid assembly with adapter removal and filtering [question]

### ISSUE THREAD

**Issue by lenorakepler** [bactopia/bactopia#413]
Hi there,

Thanks so much for such a great and comprehensive pipeline!

Apologies if this is answered elsewhere, but I noticed that if Bactopia is run with long + short reads as hybrid assemblies, the long reads do not get adapters removed with porechop or quality filtered with nanoq because meta.runtype is "hybrid" rather than "ont". I'm still new to bacterial genome assembly, so is this expected behavior in that it's not necessary for hybrid assembly, or would this ideally be done? I think it's an easy fix if it needs to occur, but just want to make sure I'm not creating more work for myself and you!

Thanks!!
Lenora

**Comment by rpetit3** [comment]
@lenorakepler great question!

There's been a few papers that suggested adapter removal isn't really necessary, but then others showing they might show up in assemblies.

But for our case here, I think we are ok skipping adapter removal for hybrid assembly. I'm assuming this since the long reads are aligned to the contigs from the short reads, and I'm guessing the adapters likely wouldn't align to the contigs.

**Comment by lenorakepler** [comment]
Makes total sense, thank you so much!

**Comment by rpetit3** [comment]
Hi @lenorakepler 

Been a while, but I decided to see how difficult it would be to ask what you suggested. In v3 of Bactopia, whenever you create a hybrid assembly with Unicycler or Dragonflye, both sets of reads under go quality control and cleanup.

I just wanted to thank you for bringing this to my attention. I think you assemblies are still OK, and there may not be much change to the final assembly, but now at aleast we can say we did everything we should.

Thanks again!
Robert
