### ISSUE TITLE
[question] main bactopia pipeline with both Merlin and abricate possible?

### ISSUE THREAD

**Issue by incoherentian** [bactopia/bactopia#436]
Hi Robert & bactopia aficionados,

Hopefully a simpler question than has been taking Robert's time recently --

Is it possible to use the main bactopia pipeline with both `--ask_merlin` and `--wf abricate` in one go?

I used Merlin for the first time today and it is epic. That said, PVL analysis seemed to be excluded from Merlin's Staphopia workflow stuff. Rather than changing prokka params I thought I'd just let VFDB do it by adding these to the working bactopia `--ask_merlin` script:
 `--wf abricate`
 `--bactopia $OUTDIR`

(where the main bactopia pipeline's outdir was also defined as  `--outdir $OUTDIR`)

...but this made bactopia try to only run the abricate workflow.

Is the only solution to run the main pipeline with `--ask_merlin` _then_ run the bactopia tools? No option to let the nf pipeline manage both simultaneously like Merlin does with so many other workflows?

Thanks as always!

**Comment by rpetit3** [comment]
> Is it possible to use the main bactopia pipeline with both --ask_merlin and --wf abricate in one go?

It is not. At the moment the only solution is to run bactopia, then the bactopia tools. 

You are correct though, there's no reason why something similar to merlin could be done for amr/virulence tools. They could  be added to merlin and be "always on" (e.g. distance to references is not taken into account).  Haha I would need to come up with some criteria for addition to merlin, otherwise I could see my self just adding them all.

Or, a separate "merlin"-like thing could be added (e.g. https://github.com/pha4ge/hAMRonization).

Or, as last measure, just run the bactopia tool.

**Comment by incoherentian** [comment]
Running bactopia tools after bactopia main and a wait in sbatch works great, and I wouldn't have minded sticking with that; just wanted to check I wasn't missing anything in the pending v3 documentation. Past-tense "minded" because some Wyomingite masochist bioinformatician brought attention to a potential cool new feature in his software's questions thread 🙊 🙈 🙉 

> Or, a separate "merlin"-like thing could be added (e.g. https://github.com/pha4ge/hAMRonization).

(and thus the [example](https://finlaymagui.re/assets/interactive_report_demo.html)!)

Maybe a bactopia >3.0.0 thing though, I don't want to be the feature-requester causing stable-release delays!

Bactopia 3 with current feature set is pretty amazing. Thanks again 🙇‍♂️
