### ISSUE TITLE
SKETCHER_MODULE problems

### ISSUE THREAD

**Issue by lingbingzeng1985** [bactopia/bactopia#460]
Here is the report:
[6e/c7a598] NOTE: Process `BACTOPIA:SKETCHER:SKETCHER_MODULE (K73)` terminated with an error exit status (1) -- Execution is retried (1)

**Comment by rpetit3** [comment]
Hi @lingbingzeng1985 

In the directory you ran  Bactopia there should be a file called `.nextflow.log`, can you share that with me?

Thank you!
Robert

**Comment by lingbingzeng1985** [comment]
It seems working now. The reason might be I do not finish the process of dataset. I just updated the edition to 3.0, but I do not find dataset step in this edition. So I used the "dataset" process at first. Thanks a lot.

**Comment by rpetit3** [comment]
Hi @lingbingzeng1985 

I've release [Bactopia v3.0.1](https://bactopia.github.io/latest/changelog/#v301-bactopiabactopia-thats-my-girl-20240325). Since I had previously marked this as "fixed" (haha my reminder to close after the next release!), I will go ahead and close this, please feel free to reopen if you think it should still be open.

Also, it would be super useful if took the time to complete my [2024 Bactopia Usage Survey](https://forms.gle/BA2BDHRQvZtpVcD38). 

Thank you so much!
Robert
