### ISSUE TITLE
wf snippy fail

### ISSUE THREAD

**Issue by ju6lio** [bactopia/bactopia#465]
**Description**

Good morning!

I've been using Bactopia without problems this past month for assembling, ask-merlin module, abricate module and pangenome wf.  My problem appeared when trying to use the snippy wf, as every time I've tried to use it, I keep getting the same fail errors. The error dictates the following: 

FYI I'm changing the numerals for the word because .md takes it as a title.

_command exit status:
  2

Command output:
  LOCUS       SPRLISCIII0930-08sNsp_1 2030447 bp   DNA    linear       08-NOV-2023

Command error:
executor >  local (11)
[91/79603d] process > BACTOPIATOOLS:SNIPPY:SNIPPY_RUN (5031_S49 - SPRLISCIII0930-08sNs) [ 90%] 10 of 11, failed: 10, retries: 9
[-        ] process > BACTOPIATOOLS:SNIPPY:SNIPPY_CORE                                  -
[-        ] process > BACTOPIATOOLS:SNIPPY:SNPDISTS                                     -
[-        ] process > BACTOPIATOOLS:SNIPPY:GUBBINS:GUBBINS_MODULE                       -
[-        ] process > BACTOPIATOOLS:SNIPPY:IQTREE:IQTREE_MODULE                         -
[-        ] process > BACTOPIATOOLS:CUSTOM_DUMPSOFTWAREVERSIONS                         -
ERROR ~ Error executing process > 'BACTOPIATOOLS:SNIPPY:SNIPPY_RUN (5029_S48 - SPRLISCIII0930-08sNs)'

Caused by:
  Process `BACTOPIATOOLS:SNIPPY:SNIPPY_RUN (5029_S48 - SPRLISCIII0930-08sNs)` terminated with an error exit status (2)

Command executed:

  if [ "false" == "true" ]; then
      gzip -c -d SPRLISCIII0930-08sNs.gbf > SPRLISCIII0930-08sNs.gbf
  fi
  
  if ! head -n 1 SPRLISCIII0930-08sNs.gbf | grep "^LOCUS"; then
      echo "ERROR: Reference file (SPRLISCIII0930-08sNs.gbf) does not appear to be a GenBank file"
      exit 1
  fi
  
  snippy \
      --mapqual 60 --basequal 13 --mincov 10 --minfrac 0 --minqual 100 --maxsoft 10 \
      --cpus 4 \
      --outdir 5029_S48 \
      --reference SPRLISCIII0930-08sNs.gbf \
      --prefix 5029_S48 \
      --R1 5029_S48_R1.fastq.gz --R2 5029_S48_R2.fastq.gz
  
   (numeral) Add GenBank annotations
  vcf-annotator 5029_S48/5029_S48.vcf SPRLISCIII0930-08sNs.gbf > 5029_S48/5029_S48.annotated.vcf
  
  (numeral) Get per-base coverage
  grep "^##contig" 5029_S48/5029_S48.vcf > 5029_S48/5029_S48.full-coverage.txt
  genomeCoverageBed -ibam 5029_S48/5029_S48.bam -d >> 5029_S48/5029_S48.full-coverage.txt
  cleanup-coverage.py 5029_S48/5029_S48.full-coverage.txt > 5029_S48/5029_S48.coverage.txt
  rm 5029_S48/5029_S48.full-coverage.txt
  
  (numeral) Mask low coverage regions
  mask-consensus.py \
      5029_S48 \
      SPRLISCIII0930-08sNs \
      5029_S48/5029_S48.consensus.subs.fa \
      5029_S48/5029_S48.subs.vcf \
      5029_S48/5029_S48.coverage.txt \
      --mincov 10 > 5029_S48/5029_S48.consensus.subs.masked.fa
  
  (numeral) Clean Up
  rm -rf 5029_S48/reference 5029_S48/ref.fa* 5029_S48/5029_S48.vcf.gz*
  
  if [[ false == "false" ]]; then
      find 5029_S48/ -type f |             grep -v -E "\.bam$|\.bai$|\.log$|\.txt$|\.html$|\.tab$" |             xargs -I {} pigz -n --best -p 4 {}
      pigz -n --best -p 4 5029_S48/5029_S48.coverage.txt
  fi
  mv 5029_S48/ results/
  mv results/*.log ./
  
  cat <<-END_VERSIONS > versions.yml
  "BACTOPIATOOLS:SNIPPY:SNIPPY_RUN":
      bedtools: $(echo $(bedtools --version 2>&1) | sed 's/bedtools v//')
      pigz: $(echo $(pigz --version 2>&1) | sed 's/pigz //')
      snippy: $(echo $(snippy --version 2>&1) | sed 's/^.*snippy //')
      vcf-annotator: $(echo $(vcf-annotator --version 2>&1) | sed 's/vcf-annotator.py //')
  END_VERSIONS

Command exit status:
  2

Command output:
  LOCUS       SPRLISCIII0930-08sNsp_1 2030447 bp   DNA    linear       08-NOV-2023

Command error:
  [M::mem_pestat] low and high boundaries for proper pairs: (1, 10638)
  [M::mem_pestat] analyzing insert size distribution for orientation RR...
  [M::mem_pestat] (25, 50, 75) percentile: (526, 4999, 5143)
  [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 14377)
  [M::mem_pestat] mean and std.dev: (3301.82, 2191.61)
  [M::mem_pestat] low and high boundaries for proper pairs: (1, 18994)
  [M::mem_pestat] skip orientation FF
  [M::mem_pestat] skip orientation RF
  [M::mem_pestat] skip orientation RR
  [M::mem_process_seqs] Processed 272072 reads in 14.108 CPU sec, 3.350 real sec
  [samclip] Processed 900000 records...
  [samclip] Processed 1000000 records...
  [M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (42, 125186, 52, 39)
  [M::mem_pestat] analyzing insert size distribution for orientation FF...
  [M::mem_pestat] (25, 50, 75) percentile: (544, 4979, 5086)
  [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 14170)
  [M::mem_pestat] mean and std.dev: (3092.76, 2227.84)
  [M::mem_pestat] low and high boundaries for proper pairs: (1, 18712)
  [M::mem_pestat] analyzing insert size distribution for orientation FR...
  [M::mem_pestat] (25, 50, 75) percentile: (202, 260, 325)
  [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 571)
  [M::mem_pestat] mean and std.dev: (265.26, 93.36)
  [M::mem_pestat] low and high boundaries for proper pairs: (1, 694)
  [M::mem_pestat] analyzing insert size distribution for orientation RF...
  [M::mem_pestat] (25, 50, 75) percentile: (130, 1164, 2325)
  [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 6715)
  [M::mem_pestat] mean and std.dev: (1391.14, 1567.90)
  [M::mem_pestat] low and high boundaries for proper pairs: (1, 8910)
  [M::mem_pestat] analyzing insert size distribution for orientation RR...
  [M::mem_pestat] (25, 50, 75) percentile: (1119, 5000, 5156)
  [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 13230)
  [M::mem_pestat] mean and std.dev: (3417.41, 2178.21)
  [M::mem_pestat] low and high boundaries for proper pairs: (1, 17267)
  [M::mem_pestat] skip orientation FF
  [M::mem_pestat] skip orientation RF
  [M::mem_pestat] skip orientation RR
  [M::mem_process_seqs] Processed 272298 reads in 13.608 CPU sec, 3.378 real sec
  [samclip] Processed 1100000 records...
  [samclip] Processed 1200000 records...
  [samclip] Processed 1300000 records...
  [main] Version: 0.7.17-r1188
  [main] CMD: bwa mem -Y -M -R @RG\tID:5029_S48\tSM:5029_S48 -t 4 reference/ref.fa /home/julio/Desktop/Wgs/prueba3s8/5029_S48/main/qc/5029_S48_R1.fastq.gz /home/julio/Desktop/Wgs/prueba3s8/5029_S48/main/qc/5029_S48_R2.fastq.gz
  [main] Real time: 17.212 sec; CPU: 67.867 sec
  [samclip] Total SAM records 1367776, removed 51707, allowed 62821, passed 1316069
  [samclip] Header contained 3 lines
  [samclip] Done.
  [11:52:50] Running: samtools index 5029_S48.bam 2>> 5029_S48.log
  [11:52:51] Running: fasta_generate_regions.py reference/ref.fa.fai 294909 > reference/ref.txt 2>> 5029_S48.log
  [11:52:51] Running: freebayes-parallel reference/ref.txt 4 -p 2 -P 0 -C 2 -F 0.05 --min-coverage 10 --min-repeat-entropy 1.0 -q 13 -m 60 --strict-vcf   -f reference/ref.fa 5029_S48.bam > 5029_S48.raw.vcf 2>> 5029_S48.log
  [11:52:56] Error running command, check 5029_S48/5029_S48.log_

**When checking the 5029_S48.log file:** I found the following information at the end of the file:

vcfuniq: error while loading shared libraries: libtabixpp.so.0: cannot open shared object file: No such file or directory
vcfstreamsort: error while loading shared libraries: libtabixpp.so.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/julio/.bactopia/conda/bioconda--bactopia-variants-1.0.1/bin/vcffirstheader", line 17, in <module>
    print(line.strip())
BrokenPipeError: [Errno 32] Broken pipe

I deleted the snippy module env:
/home/julio/.bactopia/conda/bioconda--bactopia-variants-1.0.1  
so Bactopia could not detect it and had to install it again. unfortunately, it did not work properly.

**Steps to Reproduce**

I tried first directly with a lot of the config parameters, but when having the same error all the time I tried again using the most possible simple snippy with only 3 samples:

```
 bactopia --wf snippy --bactopia /home/julio/Desktop/Wgs/prueba3s8  --reference /home/julio/Desktop/Wgs/SPRLISCIII0930-08sNs.gbf

```

**Expected Behavior**

To have a correct output of the snippy wf

**Execution Environment**

- Bactopia Version: bactopia 3.0.0
- OS: Ubuntu
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
- Environment: conda

Thank you so much for the help!!!

Best regards,

Julio

**Comment by ju6lio** [comment]
[nextflow.log.txt](https://github.com/bactopia/bactopia/files/13486746/nextflow.log.txt)
Adding the nextflow.log just in case!

Thank you!

**Comment by Kokejuli** [comment]
Hello @ju6lio !

I found the same error, I think there has to be an issue of dependencies, specially with libvcflib1. Nevertheless, I solve the problem installing in local again the libvcflib1.

`apt get update
apt get install libvcflib1`

I hope this will be helpful for you meanwhile the developers try to fix it :)

**Comment by ju6lio** [comment]
> Hello @ju6lio !
> 
> I found the same error, I think there has to be an issue of dependencies, specially with libvcflib1. Nevertheless, I solve the problem installing in local again the libvcflib1.
> 
> `apt-get update` `apt-get install libvcflib1`
> 
> I hope this will be helpful for you meanwhile the developers try to fix it :)



> Hello @ju6lio !
> 
> I found the same error, I think there has to be an issue of dependencies, specially with libvcflib1. Nevertheless, I solve the problem installing in local again the libvcflib1.
> 
> `apt-get update` `apt-get install libvcflib1`
> 
> I hope this will be helpful for you meanwhile the developers try to fix it :)

I've installed the libvcflib1 locally and now snippy works without a problem

Thank you so much for the temporal fixation!!!

Julio

**Comment by Clr27** [comment]
Hello @Kokejuli and @ju6lio,  
I am having the same problem since switching to Bactopia v3.  I used the fix given above ('apt-get update', then 'sudo apt-get install libvcflib1') and got further (thank you), but now have a new error 'AttributeError: 'SeqFeature' object has no attribute 'strand'.  I am using a downloaded genbank (full, .gb) file that worked for Snippy in Bactopia v2. Any ideas?

**Comment by lfenske-93** [comment]
Hi, having the same problem and unfortunately can't install/update `libvcflib1` by myself on our shared system.

I look forward to any suggestions for solutions.

**Comment by Clr27** [comment]
@rpetit3 Hope all well, just wondering if any update on a solution for this bug? I need to re-do some trees so monitoring.  Cheers.

**Comment by rpetit3** [comment]
Apologies, this one slipped through the cracks.

By chance do you have Docker or Singularity available to be used?

**Comment by Clr27** [comment]
@rpetit3 Thanks for getting back to me.  I thought that's what may have happened.  Currently don't have either, but could install if needed.

**Comment by rpetit3** [comment]
OK, I'll see if I can replicate the issue using Conda.  Docker or Singularity are likely to be more stable.

Although with the latest one (`'AttributeError: 'SeqFeature' object has no attribute 'strand'`), would it be possible to share the genbank file? That seems like it might be an issue with the GenBank file

**Comment by Clr27** [comment]
Unfortunately unable to upload here - says file type not supported. It a GenBank (full) downloaded from https://www.ncbi.nlm.nih.gov/nuccore/CP003200.  I used the one that worked previously, and then re-downloaded and tried again.

**Comment by rpetit3** [comment]
Would it be possible to share the `conda env export` output for this Snippy environment. I'd like to compare what I have against others

**Comment by Clr27** [comment]
[BactopiaEnv.txt](https://github.com/bactopia/bactopia/files/14059948/BactopiaEnv.txt)
Sorry for slow response

**Comment by Clr27** [comment]
Probably unrelated, but I just got Snippy to work directly when I converted the Bactopia .fna.gz files to .fasta files.

**Comment by brross60** [comment]
**Description**
I have done assembly and pangenome analysis (Roary) with bacteria v3. My bug changes morphology via a point mutation in 1 of 2 genes. I would like to align and generate a phylogenic tree based on these genes. I am trying to do snippy with a self made gbk of the genes of interest. I have tried everything and snippy won't recognize the my custom or even the full downloaded gbk. I tried other corrections suggested update of libvcflib1, download it locally via conda in the same environment, update snippy in same environment. Any suggestions?

**Steps to Reproduce**

bactopia --wf snippy --bactopia /storage/scratch1/9/xxx/EM/bactopiaspadesspe
ces/ --condadir /storage/scratch1/9/xxx/bactopia_setup/ --include test.txt --outdir test --reference genomic.gbk 


If this looks wrong, now's your chance to back out (CTRL+C 3 times).
Sleeping for 5 seconds...
--------------------------------------------------------------------
executor >  local (3)
executor >  local (4)
[e8/fef43d] process > BACTOPIATOOLS:SNIPPY:SNIPPY_RUN (EN2 - genomic) [ 50%] 2 of 4, failed: 2, retries: 2
executor >  local (4)
[e8/fef43d] process > BACTOPIATOOLS:SNIPPY:SNIPPY_RUN (EN2 - genomic) [ 50%] 2 of 4, failed: 2, retries: 2
executor >  local (5)
executor >  local (6)
[1b/456ec7] process > BACTOPIATOOLS:SNIPPY:SNIPPY_RUN (EN2 - genomic) [ 66%] 4 of 6, failed: 4, retries: 4
executor >  local (7)
executor >  local (8)
[f5/d8fba6] process > BACTOPIATOOLS:SNIPPY:SNIPPY_RUN (EN2 - genomic) [ 75%] 6 of 8, failed: 6, retries: 6
executor >  local (8)
[f5/d8fba6] process > BACTOPIATOOLS:SNIPPY:SNIPPY_RUN (EN2 - genomic) [ 75%] 6 of 8, failed: 6, retries: 6
[-        ] process > BACTOPIATOOLS:SNIPPY:SNIPPY_CORE                -
[-        ] process > BACTOPIATOOLS:SNIPPY:SNPDISTS                   -
[-        ] process > BACTOPIATOOLS:SNIPPY:GUBBINS:GUBBINS_MODULE     -
[-        ] process > BACTOPIATOOLS:SNIPPY:IQTREE:IQTREE_MODULE       -
[-        ] process > BACTOPIATOOLS:CUSTOM_DUMPSOFTWAREVERSIONS       -
ERROR ~ Error executing process > 'BACTOPIATOOLS:SNIPPY:SNIPPY_RUN (EN1 - genomic)'
Caused by:
  Process `BACTOPIATOOLS:SNIPPY:SNIPPY_RUN (EN1 - genomic)` terminated with an error exit status (2)
Command executed:
  if [ "false" == "true" ]; then
      gzip -c -d genomic.gbk > genomic.gbk
  fi
  
  if ! head -n 1 genomic.gbk | grep "^LOCUS"; then
      echo "ERROR: Reference file (genomic.gbk) does not appear to be a GenBank file"
      exit 1
  fi
  
  snippy \
      --mapqual 60 --basequal 13 --mincov 10 --minfrac 0 --minqual 100 --maxsoft 10 \
      --cpus 4 \
      --outdir EN1 \
      --reference genomic.gbk \
      --prefix EN1 \
      --R1 EN1_R1.fastq.gz --R2 EN1_R2.fastq.gz
  
  # Add GenBank annotations
  vcf-annotator EN1/EN1.vcf genomic.gbk > EN1/EN1.annotated.vcf
  
  # Get per-base coverage
  grep "^##contig" EN1/EN1.vcf > EN1/EN1.full-coverage.txt
  genomeCoverageBed -ibam EN1/EN1.bam -d >> EN1/EN1.full-coverage.txt
  cleanup-coverage.py EN1/EN1.full-coverage.txt > EN1/EN1.coverage.txt
  rm EN1/EN1.full-coverage.txt
  
  # Mask low coverage regions
  mask-consensus.py \
      EN1 \
      genomic \
      EN1/EN1.consensus.subs.fa \
      EN1/EN1.subs.vcf \
      EN1/EN1.coverage.txt \
      --mincov 10 > EN1/EN1.consensus.subs.masked.fa
  
  # Clean Up
  rm -rf EN1/reference EN1/ref.fa* EN1/EN1.vcf.gz*
  
  if [[ false == "false" ]]; then
      find EN1/ -type f |             grep -v -E "\.bam$|\.bai$|\.log$|\.txt$|\.html$|\.tab$" |             xargs -I {} pigz -n --best -p 4 {}
      pigz -n --best -p 4 EN1/EN1.coverage.txt
  fi
  mv EN1/ results/
  mv results/*.log ./
  
  cat <<-END_VERSIONS > versions.yml
  "BACTOPIATOOLS:SNIPPY:SNIPPY_RUN":
      bedtools: $(echo $(bedtools --version 2>&1) | sed 's/bedtools v//')
      pigz: $(echo $(pigz --version 2>&1) | sed 's/pigz //')
      snippy: $(echo $(snippy --version 2>&1) | sed 's/^.*snippy //')
      vcf-annotator: $(echo $(vcf-annotator --version 2>&1) | sed 's/vcf-annotator.py //')
  END_VERSIONS

Command exit status:
  2

Command output:
  LOCUS       CU458896             5067172 bp    DNA     circular BCT 27-FEB-2015

Command error:
  [samclip] Processed 1900000 records...
  [samclip] Processed 2000000 records...
  [M::process] read 296112 sequences (40000263 bp)...
  [M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 144760, 0, 1)
  [M::mem_pestat] skip orientation FF as there are not enough pairs
  [M::mem_pestat] analyzing insert size distribution for orientation FR...
  [M::mem_pestat] (25, 50, 75) percentile: (133, 199, 283)
  [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 583)
  [M::mem_pestat] mean and std.dev: (212.87, 104.13)
  [M::mem_pestat] low and high boundaries for proper pairs: (1, 733)
  [M::mem_pestat] skip orientation RF as there are not enough pairs
  [M::mem_pestat] skip orientation RR as there are not enough pairs
  [M::mem_process_seqs] Processed 295570 reads in 14.533 CPU sec, 3.433 real sec
  [samclip] Processed 2100000 records...
  [samclip] Processed 2200000 records...
  [samclip] Processed 2300000 records...
  [M::process] read 20638 sequences (2747554 bp)...
  [M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 145009, 3, 0)
  [M::mem_pestat] skip orientation FF as there are not enough pairs
  [M::mem_pestat] analyzing insert size distribution for orientation FR...
  [M::mem_pestat] (25, 50, 75) percentile: (132, 197, 281)
  [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 579)
  [M::mem_pestat] mean and std.dev: (211.60, 103.34)
  [M::mem_pestat] low and high boundaries for proper pairs: (1, 728)
  [M::mem_pestat] skip orientation RF as there are not enough pairs
  [M::mem_pestat] skip orientation RR as there are not enough pairs
  [M::mem_process_seqs] Processed 296112 reads in 14.499 CPU sec, 3.564 real sec
  [samclip] Processed 2400000 records...
  [M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 10114, 0, 0)
  [M::mem_pestat] skip orientation FF as there are not enough pairs
  [M::mem_pestat] analyzing insert size distribution for orientation FR...
  [M::mem_pestat] (25, 50, 75) percentile: (124, 188, 274)
  [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 574)
  [M::mem_pestat] mean and std.dev: (205.04, 103.44)
  [M::mem_pestat] low and high boundaries for proper pairs: (1, 724)
  [M::mem_pestat] skip orientation RF as there are not enough pairs
  [M::mem_pestat] skip orientation RR as there are not enough pairs
  [M::mem_process_seqs] Processed 20638 reads in 1.101 CPU sec, 0.259 real sec
  [samclip] Processed 2500000 records...
  [samclip] Processed 2600000 records...
  [main] Version: 0.7.17-r1188
  [main] CMD: bwa mem -Y -M -R @RG\tID:EN1\tSM:EN1 -t 4 reference/ref.fa /storage/scratch1/9/bross60/EM/bactopiaspadesspeces/EN1/main/qc/EN1_R1.fastq.gz /storage/scratch1/9/bross60/EM/bactopiaspadesspeces/EN1/main/qc/EN1_R2.fastq.gz
  [main] Real time: 34.219 sec; CPU: 137.819 sec
  [samclip] Total SAM records 2686498, removed 31963, allowed 17131, passed 2654535
  [samclip] Header contained 4 lines
  [samclip] Done.
  [20:41:34] Running: samtools index EN1.bam 2>> EN1.log
  [20:41:35] Running: fasta_generate_regions.py reference/ref.fa.fai 739355 > reference/ref.txt 2>> EN1.log
  [20:41:35] Running: freebayes-parallel reference/ref.txt 4 -p 2 -P 0 -C 2 -F 0.05 --min-coverage 10 --min-repeat-entropy 1.0 -q 13 -m 60 --strict-vcf   -f reference/ref.fa EN1.bam > EN1.raw.vcf 2>> EN1.log
  [20:41:49] Error running command, check EN1/EN1.log

Work dir:
  /storage/scratch1/9/bross60/EM/bactopiaspadesspeces/work/84/56442cf17d4ebed555f43d1fda5ca7

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
 -- Check '.nextflow.log' file for details

**Expected Behavior**
Run snippy and get a tree.

**Execution Environment**

- Bactopia Version: 3
- OS: server with scheduler
- Environment: conda, cluster

**Comment by rpetit3** [comment]
@brross60  can you by chance use singularity/apptainer on your cluster?

**Comment by pvanheus** [comment]
I saw the same error (` libtabixpp.so.0: cannot open shared object file: No such file or directory`) in a workshop yesterday. This was using `conda` on a shared system where Singularity wasn't working and no user-led install was possible. The problem seems to be in the `bactopia-variants` environment where `vcflib` installs a newer `libtabixpp.so` than the `vcfuniq` wants. The `bactopia-variants` package depends on `vcflib >=1.0.0_rc3,<=1.0.2`. To reproduce this problem:

```bash
conda create -n vcflib vcflib=1.0.2
conda activate vcflib
vcfuniq
```

The same `vcfuniq: error while loading shared libraries: libtabixpp.so.0: cannot open shared object file: No such file or directory` errors shows up. This problem has been [reported](https://github.com/bioconda/bioconda-recipes/issues/46114) over on bioconda with the `snippy` recipe which is very similar to the `bactopia variants` one. I have commented on a possible solution over there. I don't know how to change how `bactopia` builds its conda environments but I will try and test this fix with standalone snippy soon.

**Comment by rpetit3** [comment]
Hello everyone!

I've release [Bactopia v3.0.1](https://bactopia.github.io/latest/changelog/#v301-bactopiabactopia-thats-my-girl-20240325)., which should fix this issue with Snippy. If it has not, please feel free to reopen this issue!

Also, it would be super useful if you took the time to complete my [2024 Bactopia Usage Survey](https://forms.gle/BA2BDHRQvZtpVcD38). 

Thank you so much!
Robert
