### ISSUE TITLE
Error creating Conda environment

### ISSUE THREAD

**Issue by crisp3342** [bactopia/bactopia#469]
**Description**
While running the test on bactopia, there is an error creating conda environment
.

**Steps to Reproduce**
```
bactopia ...
bactopia tools ...
!!ERROR!!
```

**Expected Behavior**
A description of what is expected to happen.

**Execution Environment**

- Bactopia Version: [output from `bactopia version`]
- OS: [e.g. Mac, Ubuntu, etc...]
- Environment: [e.g. conda, cluster, container, etc...]

**Additional Information**
Any other information you think might be helpful in squashing this bug.

**Comment by IanaAmke** [comment]
Going through the same issue on macOS Sonoma (14.2.1 (23C71))

**Comment by rpetit3** [comment]
Hi @crisp3342 - Can you share more information on your system?

Hi @IanaAmke - Is your Mac Intel or Apple Silicon?

**Comment by IanaAmke** [comment]
It's Apple Silicon - Apple M2 Pro

**Comment by rpetit3** [comment]
Hi @IanaAmke

Unfortunately, out the box Bactopia will not work on the Apple Silicon machines due to many of the Conda packages not having a build for Apple Silicon (its being worked on though!).

As an alternative, can you use Docker on you Macbook?

Thanks, 
Robert

**Comment by IanaAmke** [comment]
Hi @rpetit3, I tried using Docker, and that worked perfectly. Thanks for the suggestion!

**Comment by rpetit3** [comment]
Hi @IanaAmke 

I've release [Bactopia v3.0.1](https://bactopia.github.io/latest/changelog/#v301-bactopiabactopia-thats-my-girl-20240325). Since I had previously marked this as "fixed" (haha my reminder to close after the next release!), I will go ahead and close this, please feel free to reopen if you think it should still be open.

Also, it would be super useful if took the time to complete my [2024 Bactopia Usage Survey](https://forms.gle/BA2BDHRQvZtpVcD38). 

Thank you so much!
Robert
