### ISSUE TITLE
Include assembly genome in the pipeline

### ISSUE THREAD

**Issue by felipe-mansoldo** [bactopia/bactopia#471]
Dear all,
Congratulations on the development of this pipeline, I have had great results.
Would it be possible to download an assembly to enter at the end of the pipeline and perform Antimicrobial Resistance analyses, for example?

genome assembly
https://www.ebi.ac.uk/ena/browser/view/GCA_024653105.1

**Execution Environment**
- Bactopia Version: bactopia 3.0.0
- OS: Ubuntu 22
- Environment: I tried in mamba and conda

**Comment by rpetit3** [comment]
Hi @felipe-mansoldo 

Thank you for the motivation! There are a few things going on here.

So, `bactopia search` will only retrieve available samples from ENA/SRA, so the raw FASTQ reads. It doesn't query NCBI Assembly. That should be your issue with the empty files, as it didn't find anything. Do you think it would be useful if I added a warning, something like "Your query did not retrieve any results from ENA or SRA"?

However, you can still use your Assembly accession. Easiest, since its just a single accession, would be to use `--accession` which supports a NCBI Assembly accession:
```
bactopia ... --accession GCA_024653105 ...
```

Let me know if this doesn't work for! Also, if you have any feedback, please feel free to share it with me!

Thanks again,
Robert

**Comment by felipe-mansoldo** [comment]
Dear Robert,
Thanks for the quick response, before seeing it I had edited the issue.
I removed the "bug" in the title. 
You're right, it's just that I wanted to include assembly genomes in the pipeline.
I'll try the way you mentioned and let you know!
thanks!

**Comment by felipe-mansoldo** [comment]
Dear @rpetit3 
For experimentation I ran the code you suggested, and I had problems. Look:
`
bactopia  --accession GCA_024653105
`
response:
```

executor >  local (5)
[3e/625893] process > BACTOPIA:DATASETS                             [  0%] 0 of 1
[2f/d9f11d] process > BACTOPIA:GATHER:GATHER_MODULE (GCA_024653105) [ 75%] 3 of 4, failed: 3, retries: 3
[-        ] process > BACTOPIA:GATHER:CSVTK_CONCAT                  -
[-        ] process > BACTOPIA:QC:QC_MODULE                         -
[-        ] process > BACTOPIA:ASSEMBLER:ASSEMBLER_MODULE           -
[-        ] process > BACTOPIA:ASSEMBLER:CSVTK_CONCAT               -
[-        ] process > BACTOPIA:SKETCHER:SKETCHER_MODULE             -
[-        ] process > BACTOPIA:ANNOTATOR:PROKKA_MODULE              -
[-        ] process > BACTOPIA:AMRFINDERPLUS:AMRFINDERPLUS_RUN      -
[-        ] process > BACTOPIA:AMRFINDERPLUS:GENES_CONCAT           -
[-        ] process > BACTOPIA:AMRFINDERPLUS:PROTEINS_CONCAT        -
[-        ] process > BACTOPIA:MLST:MLST_MODULE                     -
[-        ] process > BACTOPIA:MLST:CSVTK_CONCAT                    -
[-        ] process > BACTOPIA:DUMPSOFTWAREVERSIONS                 -
[a6/a9e2d5] NOTE: Process `BACTOPIA:GATHER:GATHER_MODULE (GCA_024653105)` terminated with an error exit status (1) -- Execution is retried (2)
[e9/732ad4] NOTE: Missing output file(s) `GCA_024653105-meta.tsv` expected by process `BACTOPIA:GATHER:GATHER_MODULE (GCA_024653105)` -- Execution is retried (3)

ERROR ~ Error executing process > 'BACTOPIA:GATHER:GATHER_MODULE (GCA_024653105)'

Caused by:
  Process `BACTOPIA:GATHER:GATHER_MODULE (GCA_024653105)` terminated with an error exit status (1)

Command executed:

  MERGED="multiple-read-sets-merged.txt"
  mkdir -p fastqs
  mkdir -p extra

```
Any idea?
thanks

**Comment by felipe-mansoldo** [comment]
About "Do you think it would be useful if I added a warning, something like "Your query did not retrieve any results from ENA or SRA"?",
yes, that would be great,
my best

**Comment by rpetit3** [comment]
Hi @felipe-mansoldo 

OK! Finally took care of this. Originally there was a warning about empty results buried in the `*-summary.txt` file.

Instead I have changed it so that no output files are produced, and there is an explicit warning on the command-line

```
bactopia-search --query GCA_024653105
2024-01-25 22:00:31 INFO     2024-01-25 22:00:31:root:INFO - Submitting query (type - taxon_name)                                                                                                                                                                                                        search.py:472
2024-01-25 22:00:32 WARNING  2024-01-25 22:00:32:root:WARNING - GCA_024653105 did not return any results from ENA. Please verify your query is a Taxon ID, Study, BioSample, or Run accession.
```

I think will be helpful going forward, especially since no output files will be written.

**Comment by felipe-mansoldo** [comment]
Hi @rpetit3,
that's great, thank you!
