### ISSUE TITLE
abritamr bugs correction [bug]

### ISSUE THREAD

**Issue by mtruglio** [bactopia/bactopia#477]
**Description**
abritamr tool does not work due to a couple of bugs:

1) in _workflows/bactopia-tools.nf_ , line 42, replace 'ABRICATE' with 'ABRITAMR'
2) in _abritamr/main.nf_ , line 8, replace '--identity' with '--species'

After these small fixes, it works alright.

**Comment by rpetit3** [comment]
Forgot to respond, this is fixed in the dev branch and will be in next release. https://github.com/bactopia/bactopia/commit/25387e5ca2273596ae9a54f6bb11c0af9eb193e4

Thank you for letting me know about this!

**Comment by mtruglio** [comment]
Great! Thank you :)

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by rpetit3** [comment]
Hi @mtruglio 

I've release [Bactopia v3.0.1](https://bactopia.github.io/latest/changelog/#v301-bactopiabactopia-thats-my-girl-20240325). Since I had previously marked this as "fixed" (haha my reminder to close after the next release!), I will go ahead and close this, please feel free to reopen if you think it should still be open.

Also, it would be super useful if took the time to complete my [2024 Bactopia Usage Survey](https://forms.gle/BA2BDHRQvZtpVcD38). 

Thank you so much!
Robert
