### ISSUE TITLE
ncbigenomedownload is not a known workflow

### ISSUE THREAD

**Issue by ktmeaton** [bactopia/bactopia#480]
**Description**

Is the `ncbigenomedownload` module still available as in the [documentation](https://bactopia.github.io/v3.0.0/bactopia-tools/ncbigenomedownload/)? I keep getting the error `ncbigenomedownload is not a known workflow`.

**Steps to Reproduce**

```bash
# Install
micromamba create -n bactopia-3.0.0 -c conda-forge -c bioconda bactopia=3.0.0
# Run
micromamba run -n bactopia-3.0.0 bactopia --wf ncbigenomedownload

2024-02-12 13:25:30 ERROR    2024-02-12 13:25:30:root:ERROR - ncbigenomedownload is not a known workflow, skipping                                                                               download.py:541N E X T F L O W  ~  version 23.10.1
Launching `/home/user/miniconda3/envs/bactopia-3.0.0/share/bactopia-3.0.0/main.nf` [jolly_mestorf] DSL2 - revision: 0cd9f79ba7
ERROR ~ ncbigenomedownload is not an available workflow or Bactopia Tool. Use --list_wfs to see full list

 -- Check '.nextflow.log' file for details
```

**Execution Environment**

- Bactopia Version: `bactopia 3.0.0`
- OS: `Ubuntu 20.04 (WSL2)`
- Environment: `conda`

**Comment by rpetit3** [comment]
Hi @ktmeaton 

I'm going to mark this to be closed on next release. If you would like to keep it open, please feel free to respond here.

Robert

**Comment by rpetit3** [comment]
Hi @ktmeaton 

I've release [Bactopia v3.0.1](https://bactopia.github.io/latest/changelog/#v301-bactopiabactopia-thats-my-girl-20240325). Since I had previously marked this as "fixed" (haha my reminder to close after the next release!), I will go ahead and close this, please feel free to reopen if you think it should still be open.

Also, it would be super useful if took the time to complete my [2024 Bactopia Usage Survey](https://forms.gle/BA2BDHRQvZtpVcD38). 

Thank you so much!
Robert
