### ISSUE TITLE
Sample IDs vs Experiment accessions

### ISSUE THREAD

**Issue by andreaniml** [bactopia/bactopia#485]
Hi!

In the bactopia tutorial its stated that if a single Experiment has multiple Run accessions associated with it, bactopia will merge the fastq files from each run into a single set of sequences. 

I have a few BioSample IDs and I ran bactopia --search on them, however, now I face that for some (5 BioSample IDs) I have two different experiment accessions associated. 
I am unsure of what should I do. The "bactopia-accession.txt" file has all the experiment accessions fetched, including those that map to the same BioSample. Should I manually choose one?

Thanks!

**Comment by rpetit3** [comment]
Hi @andreaniml 

I totally understand your confusion, I get lost all the time in the accessions. With BioSample accessions, I understand those to be unique "samples", so having multiple experiments would suggest they originate from the same sample. Unfortunately this is not always the case. USA300 in S. aureus is a good example, often times the same BioSample is used and now hundreds on "samples" now are considered coming from the same sample. But this to me is misleading because, even if you and I isolate the same strain (e.g. USA300) they are not unique and will have genomic differences, so they shouldn't get the same BioSample.

I think you have a few options here:

1. process all the experiments
2. exactly like you suggest, randomly pick one
3. manually download with [fastq-dl](https://github.com/rpetit3/fastq-dl) and use the `--group-by-sample` parameter

I would only do the third option if you trust the data and are confident the two experiments are sequenced from the same sample. Otherwise depending on your questions, 1 and 2 should be fine.

I wish I could give you a better answer, but I tend to be cautious of using BioSamples because of this potential issue.

Cheers,
Robert

**Comment by andreaniml** [comment]
Hi! Will check over here case by case as there are few "samples" this happened. Interesting to know about the S. aureus case.
I am currently working with Salmonella, one of the BioSamples leading to different SRA experiments is linked to an assembly that seemengly used both experiments (SAMN03743832, SRA accession: SRS1526589), so this one I think I'm going to use fastq-dl manually, will check for the others.

Cheers,

Maria Luiza

**Comment by rpetit3** [comment]
Hi @andreaniml 

I've release [Bactopia v3.0.1](https://bactopia.github.io/latest/changelog/#v301-bactopiabactopia-thats-my-girl-20240325). Since I had previously marked this as "fixed" (haha my reminder to close after the next release!), I will go ahead and close this, please feel free to reopen if you think it should still be open.

Also, it would be super useful if took the time to complete my [2024 Bactopia Usage Survey](https://forms.gle/BA2BDHRQvZtpVcD38). 

Thank you so much!
Robert
