### ISSUE TITLE
error message when installing Bactopia on an HPC cluster

### ISSUE THREAD

**Issue by fransamsing** [bactopia/bactopia#486]
Hi bactopia users,

I am getting the following error after trying to install Bactopia in our HPC cluster: 

ERROR ~ Error executing process > 'BACTOPIA:GATHER:GATHER_MODULE (1)'

Caused by:
  Failed to create Conda environment
  command: conda create -c conda-forge -c bioconda --mkdir --yes --quiet --prefix /home/fsam8653/.bactopia/conda/env-a738b058e7464f0a589401ac609ecaf9 bioconda::bactopia-gather=1.0.4
  status : 137
  message:

 -- Check '.nextflow.log' file for details

    Bactopia Execution Summary
    ---------------------------
    Bactopia Version : 3.0.0
    Nextflow Version : 23.04.3
    Command Line     : nextflow run bactopia/bactopia -profile test,standard
    Resumed          : false
    Completed At     : 2024-02-19T18:01:45.146731+11:00
    Duration         : 7m 54s
    Success          : false
    Exit Code        : null
    Error Report     : Error executing process > 'BACTOPIA:GATHER:GATHER_MODULE (1)'

Caused by:
  Failed to create Conda environment
  command: conda create -c conda-forge -c bioconda --mkdir --yes --quiet --prefix /home/fsam8653/.bactopia/conda/env-a738b058e7464f0a589401ac609ecaf9 bioconda::bactopia-gather=1.0.4
  status : 137
  message:

    Launch Dir       : /home/fsam8653

[nextflow.log.txt](https://github.com/bactopia/bactopia/files/14327602/nextflow.log.txt)

log file attached.

**Comment by rpetit3** [comment]
Hi @fransamsing 

Do you by chance have access to Singularity on your HPC system?

Cheers,
Robert

**Comment by rpetit3** [comment]
Hi @fransamsing 

I've release [Bactopia v3.0.1](https://bactopia.github.io/latest/changelog/#v301-bactopiabactopia-thats-my-girl-20240325). Since there hasn't been any further communication, I will go ahead and close this, please feel free to reopen if you think it should still be open.

Also, it would be super useful if you took the time to complete my [2024 Bactopia Usage Survey](https://forms.gle/BA2BDHRQvZtpVcD38). 

Thank you so much!
Robert
