### ISSUE TITLE
[feature] Full AMRFinderPlus search combining results to get maximum information

### ISSUE THREAD

**Issue by llk578496** [bactopia/bactopia#487]
Hi @rpetit3 ,

**Related To**

- [x] Bactopia
- [x] Bactopia Tools

**Is this related to a problem?**

**Is this something you would like to see added?**
It might be a good idea to add combined nucleotide and protein searches to `amrfinderplus` to get maximum information. For example, `amrfinder -p test_prot.fa -g test_prot.gff -n test_dna.fa -O Escherichia --plus`

**Describe the solution you'd like**

**Additional Information**
[https://github.com/ncbi/amr/wiki/Running-AMRFinderPlus#examples](https://github.com/ncbi/amr/wiki/Running-AMRFinderPlus#examples)

Again, Thanks a lot for developing this amazing pipeline!

**Comment by rpetit3** [comment]
Hi @llk578496 

As of https://github.com/bactopia/bactopia/commit/a7e2c15e5e70663433710ac5ff0af87f52042151 your suggestion has been implemented. Now only a single combined report will be generated.  This change is available in be dev version, otherwise it will be in the next release

Thanks again for the suggestion!

**Comment by rpetit3** [comment]
Hi @llk578496 

Happy to report this is in the latest version of bactopia (https://github.com/bactopia/bactopia/releases/tag/v3.1.0)

Will go ahead and close,
Robert
