### ISSUE TITLE
roary module in pangenome failed [bug]

### ISSUE THREAD

**Issue by aperreault** [bactopia/bactopia#489]
**Description**
While running pangenome through Docker, received message saying roary module was terminated. 

**Steps to Reproduce**
```
bactopia --wf pangenome --use_roary --species "Staphylococcus aureus" --bactopia /Users/aperreault/ErynData/allSamples_022824/ -profile docker
[85/769ae2] NOTE: Process `BACTOPIATOOLS:PANGENOME:PG_TOOL:ROARY_MODULE (roary)` terminated with an error exit status (1) -- Execution is retried (1)
```

**Expected Behavior**
Unsure if this means everything failed and I should start again? Or pangenome will try to do the roary module again? Alternatively can I rerun pangenome starting at a different module? Also open to using PIRATE (since this is the default) if necessary)

**Execution Environment**
- Bactopia Version: v3
- OS: Mac Intel x86
- Environment: Docker

**Comment by rpetit3** [comment]
Hi @aperreault 

Remind me how much memory you provided to Docker? And how many samples are you trying to build the pangenome of?

Cheers,
Robert

**Comment by aperreault** [comment]
What is the max amount you'd suggest for running pangenome? Do you know if PIRATE would be a better option?

**Comment by rpetit3** [comment]
For these you are probably going to want to give it maybe 30gb

**Comment by aperreault** [comment]
Okay great! Thanks for all your help. I really appreciate it!

**Comment by aperreault** [comment]
@rpetit3 sorry to bother you again-- I actually only have 16GB of RAM. Can I still run pangenome with Roary?

**Comment by rpetit3** [comment]
No problem at all @aperreault!

Give it try, but if it fails give pirate or panaroo a try

**Comment by aperreault** [comment]
Thanks @rpetit3! I'm going to try pirate right off the bad.

**Comment by rpetit3** [comment]
Hi @aperreault 

I think we are good on this one, please feel free to reopen if not! Also here comes the new release message... again haha

I've release [Bactopia v3.0.1](https://bactopia.github.io/latest/changelog/#v301-bactopiabactopia-thats-my-girl-20240325). Since I had previously marked this as "fixed" (haha my reminder to close after the next release!), I will go ahead and close this, please feel free to reopen if you think it should still be open.

Also, it would be super useful if you took the time to complete my [2024 Bactopia Usage Survey](https://forms.gle/BA2BDHRQvZtpVcD38). 

Thank you so much!
Robert
