### ISSUE TITLE
Datasets [question]

### ISSUE THREAD

**Issue by ingridvanw** [bactopia/bactopia#511]
Hi Robert,

Using your pipeline a lot :) Thanks!
One question. In the past I used bactopia version v2.3.0
I downloaded the datasets for specific bacteria (staph. aureus) to a local directory and run the pipeline with 

bactopia --fastqs multiplesamples.txt --datasets datasets/ --species 'Staphylococcus aureus' --genome_size min --reference sequence.gbk --disable_auto_variants --run_checkm --ask_merlin --coverage 240 

Now I updated bactopia to version 3.0.0
Now I don't see  "build datasets" in de tutorial. Is it " automatically done" by the pipeline?
Or do you recommend still using "--datasets datasets/" if you run >100 samples?

I get a bit confused by the logging saying
[skipped] process > BACTOPIA:DATASETS [100%] 1 of 1: stored: 1 v
[74/9ba342] process > BACTOPIA:GATHER:GATHER_MODULE 
.....

And what about the reference genome? In the last version you had to put it in a specific folder. I can put it everywhere now?

Thanks in advance!

**Comment by rpetit3** [comment]
Hi @ingridvanw 

You ae correct, no need for datasets in v3. That first step will automatically download some generic datasets (amrfinderplus, sketches, mlst). 

If you are wanting to call SNPs you will now run it as a separate step.

```
bactopia <your_samples> 
bactopia --wf snippy --bactopia <your_bactopia_folder> --reference <YOUR_REFERENCE>.gbk
```

Let me know if this helps, or you have more questions!
Robert

**Comment by ingridvanw** [comment]
Hi Robert,

Oke! Thanks for your reply:)

**Comment by LaurenGonsalves** [comment]
Hi Robert, 

I am new user (love it so far), so I hope you don't mind me asking a potentially naive follow-up question to the one above...

Your paper says that bactopia has automatic reference selection for variant calling built into it (Mash, right?). How does that work for snippy's `--reference` parameter? I am working with 1000+ clinical isolates, so I am really trying how to streamline snippy. Is there a way for snippy automatically recognize the reference selection from the initial bactopia output?

**Comment by rpetit3** [comment]
Hi @LaurenGonsalves 

No issue at all asking! You are correct there used to be the automatic reference selection. But I found while it worked nicely, you would end up getting SNPs called against multiple different references and it made it hard to compare SNPs against each other because the references were different. So, this really just made it to where Snippy was being run for no useable reason, and many would end up rerunning it with a common reference.

I think in your case, I would either select a reference for your organism of interest that is commonly used. This way you could easy compare the SNPs between samples.

Or, if this is an outbreak set of samples. Maybe pick the earliest sample. 

If you are unsure on a commonly used reference, you could consider running FastANI against your samples to find a complete geneome that fits your samples.

Does this help?

**Comment by LaurenGonsalves** [comment]
Hi @rpetit3,

Thanks for the quick response. Is the option to use the automatically selected reference still available for Snipppy, at least for us to try? Understandable, if not!

We've gone back and forth on how to analyze our isolates. They are all Staph, but with them being clinical isolates and potentially quite different from eachother, we initially thought that using the closest reference for each isolate was the most appropriate option, but perhaps we need to rethink that. I'll try out FastANI--thanks for the tip!

Appreciate the help!

**Comment by rpetit3** [comment]
Hi @ingridvanw 

I think the original issue was solved. 

@LaurenGonsalves - If you don't mind making an issue with your idea that would be great.

In other news I have released a new version of Bactopia (https://github.com/bactopia/bactopia/releases/tag/v3.1.0).

I will go ahead and close this.

Cheers,
Robert
