### ISSUE TITLE
[bug] ERROR - Error creating Conda environment, 

### ISSUE THREAD

**Issue by Jeffrey-AF** [bactopia/bactopia#521]
**Description**
I was able to run 'bactopia initially, but all of the sudden it started giving me an "ERROR - Error creating Conda environment, retrying after short sleep." message with everything I try, even commands I had run before including the test. 

**Steps to Reproduce**
```
bactopia -profile test,standard

 2024-06-01 06:29:41 INFO     2024-06-01 06:29:41:root:INFO - Checking if environment pre-builds are needed (this may take a while if building for the first time)                            download.py:544
                    INFO     2024-06-01 06:29:41:root:INFO - Begin gather create to /home/jfreiberg/.bactopia/conda/bioconda--bactopia-gather-1.0.4                                          download.py:261
2024-06-01 06:30:14 ERROR    2024-06-01 06:30:14:root:ERROR - Error creating Conda environment, retrying after short sleep.                                                                  download.py:374
2024-06-01 06:30:50 ERROR    2024-06-01 06:30:50:root:ERROR - Error creating Conda environment, retrying after short sleep.                                                                  download.py:374
2024-06-01 06:31:57 ERROR    2024-06-01 06:31:57:root:ERROR - Error creating Conda environment, retrying after short sleep.                                                                  download.py:374


```

**Expected Behavior**
A description of what is expected to happen.

**Execution Environment**

- Bactopia Version: 3.0.1
- OS: Ubuntu
- Environment: conda

**Additional Information**
I have tried everything I can think of, uninstalling and reinstalling everything (bactopia, conda), deleting and recreating environments and packages, running with max_cpus as 1, and even setting up a new environment named bactopia2 and trying there, and I still keep getting the same error message.

**Comment by Jeffrey-AF** [comment]
Here is the red text:

ERROR ~ Error executing process > 'BACTOPIA:GATHER:GATHER_MODULE (1)'

Caused by:
  Failed to create Conda environment
    command: conda create -c conda-forge -c bioconda --mkdir --yes --quiet --prefix /home/jfreiberg/.bactopia/conda/env-a738b058e7464f0a589401ac609ecaf9 bioconda::bactopia-gather=1.0.4
    status : 1
    message:
      Channels:
       - conda-forge
       - bioconda
      Platform: linux-64
      Collecting package metadata (repodata.json): ...working... done
      Solving environment: ...working... done
      
      ## Package Plan ##
      
        environment location: /home/jfreiberg/.bactopia/conda/env-a738b058e7464f0a589401ac609ecaf9
      
        added / updated specs:
          - bioconda::bactopia-gather=1.0.4
      
      
      The following packages will be downloaded:
      
          package                    |            build
          ---------------------------|-----------------
          perl-5.32.1                | 7_hd590300_perl5        12.7 MB  conda-forge
          perl-extutils-makemaker-7.70| pl5321hd8ed1ab_0         154 KB  conda-forge
          perl-uri-5.17              | pl5321ha770c72_0          66 KB  conda-forge
          ------------------------------------------------------------
                                                 Total:        12.9 MB
      
      The following NEW packages will be INSTALLED:
      
        _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge 
        _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-2_gnu 
        alsa-lib           conda-forge/linux-64::alsa-lib-1.2.7.2-h166bdaf_0 
        appdirs            conda-forge/noarch::appdirs-1.4.4-pyh9f0ad1d_0 
        art                bioconda/linux-64::art-2016.06.05-he1d7d6f_6 
        bactopia-gather    bioconda/noarch::bactopia-gather-1.0.4-hdfd78af_0 
        bbmap              bioconda/linux-64::bbmap-39.06-h92535d8_1 
        biopython          conda-forge/linux-64::biopython-1.77-py38h1e0a361_1 
        brotli-python      conda-forge/linux-64::brotli-python-1.1.0-py38h17151c0_1 
        bzip2              conda-forge/linux-64::bzip2-1.0.8-hd590300_5 
        c-ares             conda-forge/linux-64::c-ares-1.28.1-hd590300_0 
        ca-certificates    conda-forge/linux-64::ca-certificates-2024.2.2-hbcca054_0 
        cairo              conda-forge/linux-64::cairo-1.16.0-ha61ee94_1014 
        capnproto          conda-forge/linux-64::capnproto-1.0.2-h2b92303_1 
        certifi            conda-forge/noarch::certifi-2024.2.2-pyhd8ed1ab_0 
        charset-normalizer conda-forge/noarch::charset-normalizer-3.3.2-pyhd8ed1ab_0 
        click              conda-forge/noarch::click-8.1.7-unix_pyh707e725_0 
        colorama           conda-forge/noarch::colorama-0.4.6-pyhd8ed1ab_0 
        coloredlogs        conda-forge/noarch::coloredlogs-15.0.1-pyhd8ed1ab_3 
        coreutils          conda-forge/linux-64::coreutils-9.5-hd590300_0 
        curl               conda-forge/linux-64::curl-8.8.0-he654da7_0 
        executor           conda-forge/noarch::executor-23.2-pyhd3deb0d_0 
        expat              conda-forge/linux-64::expat-2.6.2-h59595ed_0 
        fasteners          conda-forge/noarch::fasteners-0.17.3-pyhd8ed1ab_0 
        fastq-dl           bioconda/noarch::fastq-dl-2.0.4-pyhdfd78af_0 
        fastq-scan         bioconda/linux-64::fastq-scan-1.0.1-h4ac6f70_3 
        font-ttf-dejavu-s~ conda-forge/noarch::font-ttf-dejavu-sans-mono-2.37-hab24e00_0 
        font-ttf-inconsol~ conda-forge/noarch::font-ttf-inconsolata-3.000-h77eed37_0 
        font-ttf-source-c~ conda-forge/noarch::font-ttf-source-code-pro-2.038-h77eed37_0 
        font-ttf-ubuntu    conda-forge/noarch::font-ttf-ubuntu-0.83-h77eed37_2 
        fontconfig         conda-forge/linux-64::fontconfig-2.14.2-h14ed4e7_0 
        fonts-conda-ecosy~ conda-forge/noarch::fonts-conda-ecosystem-1-0 
        fonts-conda-forge  conda-forge/noarch::fonts-conda-forge-1-0 
        freetype           conda-forge/linux-64::freetype-2.12.1-h267a509_2 
        gettext            conda-forge/linux-64::gettext-0.22.5-h59595ed_2 
        gettext-tools      conda-forge/linux-64::gettext-tools-0.22.5-h59595ed_2 
        giflib             conda-forge/linux-64::giflib-5.2.2-hd590300_0 
        graphite2          conda-forge/linux-64::graphite2-1.3.13-h59595ed_1003 
        gsl                conda-forge/linux-64::gsl-2.6-he838d99_2 
        harfbuzz           conda-forge/linux-64::harfbuzz-5.3.0-h418a68e_0 
        htslib             bioconda/linux-64::htslib-1.20-h81da01d_0 
        humanfriendly      conda-forge/noarch::humanfriendly-10.0-pyhd8ed1ab_6 
        icu                conda-forge/linux-64::icu-70.1-h27087fc_0 
        idna               conda-forge/noarch::idna-3.7-pyhd8ed1ab_0 
        jpeg               conda-forge/linux-64::jpeg-9e-h0b41bf4_3 
        jq                 conda-forge/linux-64::jq-1.7.1-hd590300_0 
        keyutils           conda-forge/linux-64::keyutils-1.6.1-h166bdaf_0 
        krb5               conda-forge/linux-64::krb5-1.21.2-h659d440_0 
        lcms2              conda-forge/linux-64::lcms2-2.12-hddcbb42_0 
        ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.40-hf3520f5_1 
        libasprintf        conda-forge/linux-64::libasprintf-0.22.5-h661eb56_2 
        libasprintf-devel  conda-forge/linux-64::libasprintf-devel-0.22.5-h661eb56_2 
        libblas            conda-forge/linux-64::libblas-3.9.0-22_linux64_openblas 
        libcblas           conda-forge/linux-64::libcblas-3.9.0-22_linux64_openblas 
        libcups            conda-forge/linux-64::libcups-2.3.3-h4637d8d_4 
        libcurl            conda-forge/linux-64::libcurl-8.8.0-hca28451_0 
        libdeflate         conda-forge/linux-64::libdeflate-1.20-hd590300_0 
        libedit            conda-forge/linux-64::libedit-3.1.20191231-he28a2e2_2 
        libev              conda-forge/linux-64::libev-4.33-hd590300_2 
        libexpat           conda-forge/linux-64::libexpat-2.6.2-h59595ed_0 
        libffi             conda-forge/linux-64::libffi-3.4.2-h7f98852_5 
        libgcc-ng          conda-forge/linux-64::libgcc-ng-13.2.0-h77fa898_7 
        libgettextpo       conda-forge/linux-64::libgettextpo-0.22.5-h59595ed_2 
        libgettextpo-devel conda-forge/linux-64::libgettextpo-devel-0.22.5-h59595ed_2 
        libgfortran-ng     conda-forge/linux-64::libgfortran-ng-13.2.0-h69a702a_7 
        libgfortran5       conda-forge/linux-64::libgfortran5-13.2.0-hca663fb_7 
        libglib            conda-forge/linux-64::libglib-2.80.2-hf974151_0 
        libgomp            conda-forge/linux-64::libgomp-13.2.0-h77fa898_7 
        libiconv           conda-forge/linux-64::libiconv-1.17-hd590300_2 
        libidn2            conda-forge/linux-64::libidn2-2.3.7-hd590300_0 
        liblapack          conda-forge/linux-64::liblapack-3.9.0-22_linux64_openblas 
        libnghttp2         conda-forge/linux-64::libnghttp2-1.58.0-h47da74e_1 
        libnsl             conda-forge/linux-64::libnsl-2.0.1-hd590300_0 
        libopenblas        conda-forge/linux-64::libopenblas-0.3.27-pthreads_h413a1c8_0 
        libpng             conda-forge/linux-64::libpng-1.6.43-h2797004_0 
        libsqlite          conda-forge/linux-64::libsqlite-3.45.3-h2797004_0 
        libssh2            conda-forge/linux-64::libssh2-1.11.0-h0841786_0 
        libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-13.2.0-hc0a3c3a_7 
        libtiff            conda-forge/linux-64::libtiff-4.2.0-hf544144_3 
        libunistring       conda-forge/linux-64::libunistring-0.9.10-h7f98852_0 
        libuuid            conda-forge/linux-64::libuuid-2.38.1-h0b41bf4_0 
        libwebp-base       conda-forge/linux-64::libwebp-base-1.4.0-hd590300_0 
        libxcb             conda-forge/linux-64::libxcb-1.13-h7f98852_1004 
        libxcrypt          conda-forge/linux-64::libxcrypt-4.4.36-hd590300_1 
        libxml2            conda-forge/linux-64::libxml2-2.9.14-h22db469_4 
        libxslt            conda-forge/linux-64::libxslt-1.1.35-h8affb1d_0 
        libzlib            conda-forge/linux-64::libzlib-1.2.13-h4ab18f5_6 
        lxml               conda-forge/linux-64::lxml-4.9.1-py38h0a891b7_0 
        markdown-it-py     conda-forge/noarch::markdown-it-py-3.0.0-pyhd8ed1ab_0 
        mash               bioconda/linux-64::mash-2.3-he348c14_1 
        mdurl              conda-forge/noarch::mdurl-0.1.2-pyhd8ed1ab_0 
        ncbi-genome-downl~ bioconda/noarch::ncbi-genome-download-0.3.3-pyh7cba7a3_0 
        ncbi-vdb           bioconda/linux-64::ncbi-vdb-3.1.1-h4ac6f70_0 
        ncurses            conda-forge/linux-64::ncurses-6.5-h59595ed_0 
        numpy              conda-forge/linux-64::numpy-1.24.4-py38h59b608b_0 
        oniguruma          conda-forge/linux-64::oniguruma-6.9.9-hd590300_0 
        openjdk            conda-forge/linux-64::openjdk-17.0.3-hea3dc9f_3 
        openssl            conda-forge/linux-64::openssl-3.3.0-h4ab18f5_3 
        ossuuid            conda-forge/linux-64::ossuuid-1.6.2-hf484d3e_1000 
        pandas             conda-forge/linux-64::pandas-2.0.3-py38h01efb38_1 
        pbzip2             conda-forge/linux-64::pbzip2-1.1.13-h1fcc475_2 
        pcre2              conda-forge/linux-64::pcre2-10.43-hcad00b1_0 
        perl               conda-forge/linux-64::perl-5.32.1-7_hd590300_perl5 
        perl-alien-build   bioconda/linux-64::perl-alien-build-2.48-pl5321hec16e2b_0 
        perl-alien-libxml2 bioconda/linux-64::perl-alien-libxml2-0.17-pl5321hec16e2b_0 
        perl-business-isbn conda-forge/noarch::perl-business-isbn-3.007-pl5321hd8ed1ab_0 
        perl-business-isb~ conda-forge/noarch::perl-business-isbn-data-20210112.006-pl5321hd8ed1ab_0 
        perl-capture-tiny  conda-forge/linux-64::perl-capture-tiny-0.48-pl5321ha770c72_1 
        perl-carp          conda-forge/noarch::perl-carp-1.50-pl5321hd8ed1ab_0 
        perl-constant      conda-forge/noarch::perl-constant-1.33-pl5321hd8ed1ab_0 
        perl-exporter      conda-forge/noarch::perl-exporter-5.74-pl5321hd8ed1ab_0 
        perl-extutils-mak~ conda-forge/noarch::perl-extutils-makemaker-7.70-pl5321hd8ed1ab_0 
        perl-ffi-checklib  bioconda/noarch::perl-ffi-checklib-0.28-pl5321hdfd78af_0 
        perl-file-chdir    conda-forge/noarch::perl-file-chdir-0.1011-pl5321hd8ed1ab_0 
        perl-file-path     conda-forge/noarch::perl-file-path-2.18-pl5321hd8ed1ab_0 
        perl-file-temp     conda-forge/noarch::perl-file-temp-0.2304-pl5321hd8ed1ab_0 
        perl-file-which    conda-forge/noarch::perl-file-which-1.24-pl5321hd8ed1ab_0 
        perl-importer      conda-forge/noarch::perl-importer-0.026-pl5321hd8ed1ab_0 
        perl-parent        conda-forge/noarch::perl-parent-0.241-pl5321hd8ed1ab_0 
        perl-path-tiny     conda-forge/noarch::perl-path-tiny-0.124-pl5321hd8ed1ab_0 
        perl-pathtools     conda-forge/linux-64::perl-pathtools-3.75-pl5321h166bdaf_0 
        perl-scope-guard   conda-forge/noarch::perl-scope-guard-0.21-pl5321hd8ed1ab_0 
        perl-sub-info      conda-forge/noarch::perl-sub-info-0.002-pl5321hd8ed1ab_0 
        perl-term-table    bioconda/noarch::perl-term-table-0.016-pl5321hdfd78af_0 
        perl-test-fatal    conda-forge/linux-64::perl-test-fatal-0.016-pl5321ha770c72_0 
        perl-test-warnings conda-forge/linux-64::perl-test-warnings-0.031-pl5321ha770c72_0 
        perl-test2-suite   bioconda/noarch::perl-test2-suite-0.000145-pl5321hdfd78af_0 
        perl-try-tiny      conda-forge/linux-64::perl-try-tiny-0.31-pl5321ha770c72_0 
        perl-uri           conda-forge/linux-64::perl-uri-5.17-pl5321ha770c72_0 
        perl-xml-libxml    bioconda/linux-64::perl-xml-libxml-2.0207-pl5321h661654b_0 
        perl-xml-namespac~ conda-forge/noarch::perl-xml-namespacesupport-1.12-pl5321hd8ed1ab_0 
        perl-xml-sax       conda-forge/noarch::perl-xml-sax-1.02-pl5321hd8ed1ab_0 
        perl-xml-sax-base  conda-forge/noarch::perl-xml-sax-base-1.09-pl5321hd8ed1ab_0 
        pigz               conda-forge/linux-64::pigz-2.8-h2797004_0 
        pip                conda-forge/noarch::pip-24.0-pyhd8ed1ab_0 
        pixman             conda-forge/linux-64::pixman-0.43.2-h59595ed_0 
        property-manager   conda-forge/noarch::property-manager-3.0-py_0 
        pthread-stubs      conda-forge/linux-64::pthread-stubs-0.4-h36c2ea0_1001 
        pygments           conda-forge/noarch::pygments-2.18.0-pyhd8ed1ab_0 
        pysocks            conda-forge/noarch::pysocks-1.7.1-pyha2e5f31_6 
        pysradb            bioconda/noarch::pysradb-2.2.0-pyhdfd78af_0 
        python             conda-forge/linux-64::python-3.8.19-hd12c33a_0_cpython 
        python-dateutil    conda-forge/noarch::python-dateutil-2.9.0-pyhd8ed1ab_0 
        python-tzdata      conda-forge/noarch::python-tzdata-2024.1-pyhd8ed1ab_0 
        python_abi         conda-forge/linux-64::python_abi-3.8-4_cp38 
        pytz               conda-forge/noarch::pytz-2024.1-pyhd8ed1ab_0 
        readline           conda-forge/linux-64::readline-8.2-h8228510_1 
        rename             bioconda/noarch::rename-1.601-hdfd78af_1 
        requests           conda-forge/noarch::requests-2.32.3-pyhd8ed1ab_0 
        requests-ftp       conda-forge/noarch::requests-ftp-0.3.1-py_1 
        rich               conda-forge/noarch::rich-13.7.1-pyhd8ed1ab_0 
        rich-click         conda-forge/noarch::rich-click-1.8.2-pyhd8ed1ab_0 
        samtools           bioconda/linux-64::samtools-1.20-h50ea8bc_0 
        sed                conda-forge/linux-64::sed-4.8-he412f7d_0 
        setuptools         conda-forge/noarch::setuptools-70.0.0-pyhd8ed1ab_0 
        six                conda-forge/noarch::six-1.16.0-pyh6c4a22f_0 
        sra-tools          bioconda/linux-64::sra-tools-3.1.1-h4304569_0 
        tk                 conda-forge/linux-64::tk-8.6.13-noxft_h4845f30_101 
        tqdm               conda-forge/noarch::tqdm-4.66.4-pyhd8ed1ab_0 
        typing_extensions  conda-forge/noarch::typing_extensions-4.11.0-pyha770c72_0 
        urllib3            conda-forge/noarch::urllib3-2.2.1-pyhd8ed1ab_0 
        verboselogs        conda-forge/noarch::verboselogs-1.7-py_0 
        wget               conda-forge/linux-64::wget-1.21.4-hda4d442_0 
        wheel              conda-forge/noarch::wheel-0.43.0-pyhd8ed1ab_1 
        xmltodict          conda-forge/noarch::xmltodict-0.13.0-pyhd8ed1ab_0 
        xorg-fixesproto    conda-forge/linux-64::xorg-fixesproto-5.0-h7f98852_1002 
        xorg-inputproto    conda-forge/linux-64::xorg-inputproto-2.3.2-h7f98852_1002 
        xorg-kbproto       conda-forge/linux-64::xorg-kbproto-1.0.7-h7f98852_1002 
        xorg-libice        conda-forge/linux-64::xorg-libice-1.1.1-hd590300_0 
        xorg-libsm         conda-forge/linux-64::xorg-libsm-1.2.4-h7391055_0 
        xorg-libx11        conda-forge/linux-64::xorg-libx11-1.8.4-h0b41bf4_0 
        xorg-libxau        conda-forge/linux-64::xorg-libxau-1.0.11-hd590300_0 
        xorg-libxdmcp      conda-forge/linux-64::xorg-libxdmcp-1.1.3-h7f98852_0 
        xorg-libxext       conda-forge/linux-64::xorg-libxext-1.3.4-h0b41bf4_2 
        xorg-libxfixes     conda-forge/linux-64::xorg-libxfixes-5.0.3-h7f98852_1004 
        xorg-libxi         conda-forge/linux-64::xorg-libxi-1.7.10-h7f98852_0 
        xorg-libxrender    conda-forge/linux-64::xorg-libxrender-0.9.10-h7f98852_1003 
        xorg-libxtst       conda-forge/linux-64::xorg-libxtst-1.2.3-h7f98852_1002 
        xorg-recordproto   conda-forge/linux-64::xorg-recordproto-1.14.2-h7f98852_1002 
        xorg-renderproto   conda-forge/linux-64::xorg-renderproto-0.11.1-h7f98852_1002 
        xorg-xextproto     conda-forge/linux-64::xorg-xextproto-7.3.0-h0b41bf4_1003 
        xorg-xproto        conda-forge/linux-64::xorg-xproto-7.0.31-h7f98852_1007 
        xz                 conda-forge/linux-64::xz-5.2.6-h166bdaf_0 
        zlib               conda-forge/linux-64::zlib-1.2.13-h4ab18f5_6 
        zstd               conda-forge/linux-64::zstd-1.5.6-ha6fb4c9_0 
      
      
      InvalidArchiveError("Error with archive /media/jfreiberg/My_Book/CONDA/miniforge3/pkgs/perl-uri-5.17-pl5321ha770c72_0.conda.  You probably need to delete and re-download or re-create this file.  Message was:\n\nfailed with error: [Errno 22] Invalid argument: '/media/jfreiberg/My_Book/CONDA/miniforge3/pkgs/perl-uri-5.17-pl5321ha770c72_0/man/man3/URI::_punycode.3'")
      InvalidArchiveError("Error with archive /media/jfreiberg/My_Book/CONDA/miniforge3/pkgs/perl-extutils-makemaker-7.70-pl5321hd8ed1ab_0.conda.  You probably need to delete and re-download or re-create this file.  Message was:\n\nfailed with error: [Errno 22] Invalid argument: '/media/jfreiberg/My_Book/CONDA/miniforge3/pkgs/perl-extutils-makemaker-7.70-pl5321hd8ed1ab_0/man/man3/ExtUtils::MM_OS390.3'")
      InvalidArchiveError("Error with archive /media/jfreiberg/My_Book/CONDA/miniforge3/pkgs/perl-5.32.1-7_hd590300_perl5.conda.  You probably need to delete and re-download or re-create this file.  Message was:\n\nfailed with error: [Errno 22] Invalid argument: '/media/jfreiberg/My_Book/CONDA/miniforge3/pkgs/perl-5.32.1-7_hd590300_perl5/man/man3/Parse::CPAN::Meta.3'")



 -- Check '.nextflow.log' file for details

**Comment by rpetit3** [comment]
Hi @Jeffrey-AF 

Based on this it looks like a `conda clean -ay` might be needed, and then if still having issues a 

```
rm -rf /media/jfreiberg/My_Book/CONDA/miniforge3/pkgs/*
```

might be needed. But try the `conda clean` first.

**Comment by Jeffrey-AF** [comment]
Thanks for responding, 

I ended up solving the issue, I was trying to store pkgs on an external hard drive and that was causing issues with perl for some reason. Once I moved everything back to my main hard drive it started running fine. 

Thanks again for responding so quickly and for making such a great tool!

**Comment by ingridvanw** [comment]
Hi @rpetit3 ,

Today I wanted to create a new conda environment in order to use the newest bactopia version. I used conda in stead of mamba because of the issues mentioned above here about mamba

`conda clean -ay
conda create -n bactopia_v3.1.00
conda activate bactopia_v3.1.00
conda install bactopia
bactopia --version`
-> bactopia 3.1.00
`conda --version`
-> conda 24.1.2

mamba version (not used in this commandline, but it gaves the same error)
-> mamba 1.5.7

running bactopia
' bactopia --samples samples.txt --outdir /output/ --shovill_assembler spades --cleanup_workdir'

After 5 retries it started the pipeline. The same error about "force" is mentioned.
Never had problem with installing bactopia before.
Not sure to proceed further or solve this issue .


2025-01-31 15:33:26 INFO     2025-01-31 15:33:26:root:INFO - Checking if environment pre-builds are needed   download.py:544
                             (this may take a while if building for the first time)                                         
                    INFO     2025-01-31 15:33:26:root:INFO - Begin datasets create to                        download.py:261
                             /home/ingrid/.bactopia/conda/bioconda--gnu-wget-1.18                                           
                    ERROR    2025-01-31 15:33:26:root:ERROR - Error creating Conda environment, retrying     download.py:374
                             after short sleep.                                                                             
2025-01-31 15:33:56 ERROR    2025-01-31 15:33:56:root:ERROR - Error creating Conda environment, retrying     download.py:374
                             after short sleep.                                                                             
2025-01-31 15:34:56 ERROR    2025-01-31 15:34:56:root:ERROR - Error creating Conda environment, retrying     download.py:374
                             after short sleep.                                                                             
2025-01-31 15:36:26 ERROR    2025-01-31 15:36:26:root:ERROR - Error creating Conda environment, retrying     download.py:374
                             after short sleep.                                                                             
2025-01-31 15:38:26 ERROR    2025-01-31 15:38:26:root:ERROR - Error creating Conda environment, retrying     download.py:374
                             after short sleep.                                                                             
2025-01-31 15:40:56 ERROR    2025-01-31 15:40:56:root:ERROR - External command failed with exit code 109!        utils.py:43
                                                                                                                            
                             Command:                                                                                       
                             bash -c 'mamba create -y -p /home/ingrid/.bactopia/conda/bioconda--gnu-wget-1.18 -c            
                             conda-forge -c bioconda --force bioconda::gnu-wget=1.18'                                       
                                                                                                                            
                             **Standard error:                                                                                
                             The following argument was not expected: --force**                                               
                             Run with --help for more information.                                                          

 N E X T F L O W   ~  version 24.10.4

Launching `/home/ingrid/miniconda3/envs/denmark/share/bactopia-3.1.0/main.nf` [pedantic_bassi] DSL2 - revision: 0cd9f79ba7

MODULES: [datasets, gather, qc, assembler, sketcher, amrfinderplus, mlst]
MODULES: [datasets, gather, qc, assembler, sketcher, amrfinderplus, mlst]

--------------------------------------------
   _                _              _             
  | |__   __ _  ___| |_ ___  _ __ (_) __ _       
  | '_ \ / _` |/ __| __/ _ \| '_ \| |/ _` |   
  | |_) | (_| | (__| || (_) | |_) | | (_| |      
  |_.__/ \__,_|\___|\__\___/| .__/|_|\__,_| 
                            |_|                  
  bactopia v3.1.0
  Bactopia is a flexible pipeline for complete analysis of bacterial genomes 
---------------------------------------------
Core Nextflow options
  runName              : pedantic_bassi
  container            : quay.io/bactopia/bactopia:3.1.0
  launchDir            : /home/ingrid
  workDir              : /home/ingrid/work
  projectDir           : /home/ingrid/miniconda3/envs/denmark/share/bactopia-3.1.0
  userName             : ingrid
  profile              : standard
  configFiles          : /home/ingrid/miniconda3/envs/denmark/share/bactopia-3.1.0/nextflow.config

Required Parameters
  samples              : /media/ingrid/Elements/NTM/DEvsNL/163_Samples_Denmark_bactopia.txt

Dataset Parameters
  genome_size          : 0

QC Parameters
  adapters             : /home/ingrid/miniconda3/envs/denmark/share/bactopia-3.1.0/data/EMPTY_ADAPTERS
  phix                 : /home/ingrid/miniconda3/envs/denmark/share/bactopia-3.1.0/data/EMPTY_PHIX

Assembler Parameters
  shovill_assembler    : spades

Prokka Parameters
  proteins             : /home/ingrid/miniconda3/envs/denmark/share/bactopia-3.1.0/data/proteins.faa

Optional Parameters
  outdir               : /media/ingrid/Elements/NTM/DEvsNL/Bactopia_Denmark/

Max Job Request Parameters
  max_memory           : 64 GB
  max_time             : 2h

Nextflow Configuration Parameters
  cleanup_workdir      : true

Nextflow Profile Parameters
  condadir             : /home/ingrid/.bactopia/conda
  datasets_cache       : /home/ingrid/.bactopia/datasets
  singularity_cache_dir: /home/ingrid/.bactopia/singularity

!! Only displaying parameters that differ from the pipeline defaults !!
--------------------------------------------------------------------
If you use bactopia for your analysis please cite:

* Bactopia
  https://doi.org/10.1128/mSystems.00190-20

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

* Software dependencies
  https://bactopia.github.io/acknowledgements/
--------------------------------------------------------------------
WARN: 
WARN: Conda Disclaimer
WARN: 
WARN: If you have access to Docker or Singularity, please consider
WARN: running Bactopia using containers. The containers are less
WARN: susceptible to Conda environment related issues (e.g. version
WARN: conflicts) and errors caused by creation of conda environments
WARN: in parallel (use '--max_cpus 1' to over come this error).
WARN: 
WARN: To use containers, you can use the profile parameter
WARN:     Docker: -profile docker
WARN:     Singularity: -profile singularity
WARN: 
--------------------------------------------------------------------
WARN: Include with `addParams()` is deprecated -- pass params as a workflow or process input instead
WARN: Include with `addParams()` is deprecated -- pass params as a workflow or process input instead
WARN: Include with `addParams()` is deprecated -- pass params as a workflow or process input instead
WARN: Include with `addParams()` is deprecated -- pass params as a workflow or process input instead
WARN: Include with `addParams()` is deprecated -- pass params as a workflow or process input instead
WARN: Include with `addParams()` is deprecated -- pass params as a workflow or process input instead
WARN: Include with `addParams()` is deprecated -- pass params as a workflow or process input instead
WARN: Include with `addParams()` is deprecated -- pass params as a workflow or process input instead
WARN: Include with `addParams()` is deprecated -- pass params as a workflow or process input instead
WARN: Include with `addParams()` is deprecated -- pass params as a workflow or process input instead
WARN: Include with `addParams()` is deprecated -- pass params as a workflow or process input instead
WARN: Include with `addParams()` is deprecated -- pass params as a workflow or process input instead
xecutor >  local (23)
[skipped  ] BACTOPIA:DATASETS                                  [100%] 1 of 1, stored: 1 ✔
[65/367df9] BACTOPIA:GATHER:GATHER_MODULE (x) [  9%] 15 of 163


Thanks in advance,
Ingrid
