### ISSUE TITLE
[question] Creating a software dump after the run?

### ISSUE THREAD

**Issue by coxrs** [bactopia/bactopia#540]
Hello,

We are using Bactopia with --ask_merlin to assess group A Strep among other samples. The run throws errors at the pneumocat step, which normally wouldn't be a problem since group A isn't a S. pneumo, but it prevents the pipeline from completing the dump of software versions. I am wondering if there is a way to keep pneumocat from throwing the error or maybe run the dumpsoftwareversions separately after the run.

Thanks,
Rachel

**Comment by rpetit3** [comment]
Hi @coxrs 

I think the solution for this will be to remove pneumocat from Merlin. Let me look into this, will update soon.

Thank you for reporting this,
Robert

**Comment by rpetit3** [comment]
Fixed in https://github.com/bactopia/bactopia/commit/5dbb5fce942b6c2752f4e1e8e7e8c1b814cb41d8

In the past I recognized this issue. For Merlin, I think its best to only have programs the successfully produce negative results. PneumoCat it a good example for producing non-0 exit on negative results

This fix will be available in the next release

**Comment by rpetit3** [comment]
Hi @coxrs 

This should now be fixed in https://github.com/bactopia/bactopia/releases/tag/v3.1.0

Please let me know if your issue persists,
Robert
