### ISSUE TITLE
[feature] duplicate biosample handling

### ISSUE THREAD

**Issue by plasmid02** [bactopia/bactopia#94]
**Related To**

- [X] Bactopia
- [ ] Bactopia Tools

**Describe the solution you'd like**

option to identify experiments that have the same Biosample - keep only one based on rational criteria, e.g pFASTQ quality

(rpetit3 edited 2020-03-30 - removed template text)

**Comment by rpetit3** [comment]
`bactopia search` now allows BioSamples to be searched. It will query ENA then find all Experiment accessions associated with a BioSample. It then outputs a list of those Experiment accessions.

It would be possible to add a parameter to randomly (or based on some criteria) pick an Experiment accession in the case there are multiple Experiments to a BioSample.

Then there could just be a warning message: "EXP randomly selected from X other EXPs associated with BioSample".

Warning due to the accidental misuse of some BioSamples (e.g. USA300). I think in most cases it will be 1-to-1.

Would this work?

**Comment by rpetit3** [comment]
Added a solution for this in https://github.com/bactopia/bactopia/commit/244c0b3aa29168a47e2f026bec09a5cb105656ea Will be in the next version

```
  --biosample_subset INT
                        If a BioSample has multiple Experiments, pick a random
                        subset. (Default: Return All)
```

User will get a warning in the summary
```
LIMIT: 1000000
RESULTS: 8 (./ena-results.txt)
ILLUMINA ACCESSIONS: 1 (./ena-accessions.txt)
        WARNING: Selected 1 Experiment accession(s) from a total of 4
FILTERED ACCESSIONS: no filters applied
        MISSING FASTQS: 0
```
